marklogic/java-client-api

- src/main/java/com/marklogic/client/impl/DocumentPatchBuilderImpl.java
- src/main/java/com/marklogic/client/impl/JSONStringWriter.java
- src/test/java/com/marklogic/client/test/JSONDocumentTest.java
This patch fixes issue 249 by handling replaceValue numbers, boolean, and null correctly.
> Issue #249 fixes replaceValue with numbers or booleans

- src/main/java/com/marklogic/client/impl/JerseyServices.java
For example, the errorCode in variable "failure" might be "XDMP-SPQLNOSUCHGRAPH", but when extractErrorFields(response) is called a second time, the errorCode that ends up in the stack trace is null.
> Allow error propagation from server eval 500s

- src/test/java/com/marklogic/client/test/SPARQLManagerTest.java
Test adjustment for changes in text/csv serialization of SPARQL results.
@georgeajit , if you think this change is acceptable, I'll merge it with develop and 3.0-develop
> bug:393 Adjust test for new csv results

- CONTRIBUTING.md
Replacing references to nonexistent branch _dev_ with _develop_.
> Adjusting branch names from dev to develop

- CONTRIBUTING.md
- README.md
- pom.xml
- src/test/java/com/marklogic/client/test/BitemporalTest.java
Having to use shell scripts may confuse non-Linux/Mac contributors.
Additionally, this will use the classpath as modeled in pom.xml and avoids the
need to keep shell scripts in sync. If this gets accepted, may the
`bootstrap-test.sh`and `bootstrap-test-cygwin.sh` scripts become obsolete?
> Providing a portable variant to initialize (and teardown) a test database

- src/main/java/com/marklogic/client/io/QueryOptionsHandle.java
- src/main/java/com/marklogic/client/io/QueryOptionsListHandle.java
- src/main/java/com/marklogic/client/io/TuplesHandle.java
- src/main/java/com/marklogic/client/io/ValuesHandle.java
- src/main/java/com/marklogic/client/io/ValuesListHandle.java
Applying an initialization-on-demand holder pattern for lazy thread-safe JAXB context
initialization.
> #371 - caching JAXBContexts after initialization

- src/main/java/com/marklogic/client/alerting/RuleDefinitionList.java
- src/main/java/com/marklogic/client/impl/GraphManagerImpl.java
- src/main/java/com/marklogic/client/impl/HTTPKerberosAuthFilter.java
- src/main/java/com/marklogic/client/impl/JerseyServices.java
- src/main/java/com/marklogic/client/impl/QueryOptionsTransformExtractNS.java
- src/main/java/com/marklogic/client/impl/QueryOptionsTransformInjectNS.java
- src/main/java/com/marklogic/client/io/DocumentMetadataHandle.java
- src/test/java/com/marklogic/client/test/GraphsTest.java
- Use static methods to produce Numbers, rather than constructors.
- Avoid auto boxing. If primitives are needed, use Obj.parseXXX()
- Do not recalculate NodeList.getLength() inside of a loop. It is not
cached and is re-calculated on every invocation. Set value outside of
the loop.
- Avoid constructing new String() objects when not necessary.
- Use entrySet iterator, rather than Map.get()
> Efficiencies: avoid constructing new Objects, auto boxing, etc.

- src/main/java/com/marklogic/client/datamovement/WriteHostBatcher.java
- src/main/java/com/marklogic/client/datamovement/impl/QueryHostBatcherImpl.java
- src/main/java/com/marklogic/client/datamovement/impl/WriteHostBatcherImpl.java
- src/main/java/com/marklogic/client/datamovement/package-info.java
- src/test/java/com/marklogic/client/test/datamovement/ApplyTransformTest.java
- src/test/java/com/marklogic/client/test/datamovement/DeleteListenerTest.java
- src/test/java/com/marklogic/client/test/datamovement/ExportToWriterListenerTest.java
- src/test/java/com/marklogic/client/test/datamovement/PointInTimeQueryTest.java
- src/test/java/com/marklogic/client/test/datamovement/QueryHostBatcherIteratorTest.java
- src/test/java/com/marklogic/client/test/datamovement/QueryHostBatcherTest.java
- src/test/java/com/marklogic/client/test/datamovement/WriteHostBatcherTest.java
- src/test/java/com/marklogic/client/test/datamovement/javadocExamples/PackageExamples.java
- test-complete/src/test/java/com/marklogic/client/datamovement/functionaltests/ApplyTransformTest.java
- test-complete/src/test/java/com/marklogic/client/datamovement/functionaltests/DeleteListenerTest.java
- test-complete/src/test/java/com/marklogic/client/datamovement/functionaltests/ExportListenerTest.java
- test-complete/src/test/java/com/marklogic/client/datamovement/functionaltests/ExportToWriterListenerTest.java
- test-complete/src/test/java/com/marklogic/client/datamovement/functionaltests/StringQueryHostBatcherTest.java
- test-complete/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteHostBatcherTest.java
This fixes https://github.com/marklogic/data-movement/issues/125
Some early feedback with WriteHostBatcher was that sometimes one might want to flush without blocking for everything to complete.  Some were unsure whether to expect flush to block or not.  We decided to  remove flush and replace it with flushAndWait and flushAsync.  The method names hopefully illustrate what they do.  We discussed this in feature team meeting, but it's been a *long* time back.  Let me know if this raises any concerns.
Charles, can you merge this into entity services, then change any of your calls to writeHostBatcher.flush() to be flushAndWait() instead?  
Ajit, can you do the same and merge in this pull request when you've updated the functional tests to not use flush() any longer?
> fix #125 - breakout WriteHostBatcher.flush to flushAsync and flushAndWait

- src/main/java/com/marklogic/client/io/XMLEventReaderHandle.java
- src/main/java/com/marklogic/client/io/XMLStreamReaderHandle.java
- src/main/java/com/marklogic/client/query/StructuredQueryBuilder.java
See #747 - removed dup occurrences of "for" in the javadoc.
> issue #747: Fix some typos in the javadoc

- pom.xml
Hi @sammefford , this PR takes away some pom configuration that was useful during samplestack development.
This change to the pom is needed to smooth the way for @itsshivaverma to configure nexus deployment.  As such, we'd like to get it merged pretty soon if possible.  
Unit tests are not affected by this change, I did run them all successfully.
> Issue #831, remote site plugin from pom

- src/main/java/com/marklogic/client/impl/CombinedQueryBuilderImpl.java
- src/main/java/com/marklogic/client/impl/DocumentMetadataPatchBuilderImpl.java
- src/main/java/com/marklogic/client/impl/Utilities.java
- src/main/java/com/marklogic/client/impl/XmlFactories.java
- src/main/java/com/marklogic/client/io/DocumentMetadataHandle.java
- src/main/java/com/marklogic/client/query/StructuredQueryBuilder.java
- src/test/java/com/marklogic/client/test/CombinedQueryBuilderTest.java
Introducing `XmlFactories` as a means to retrieve a shared `XMLOutoutFactory`. Also consolidating factory initialization into a common `makeNewOutputFactory` method.
This change is intended to address the main concerns of #474.
> Caching XMLOutputFactory to improve performance (fixes #474)

- src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- src/test/java/com/marklogic/client/test/RowManagerTest.java
fixes #867.  Targets upcoming version 4.0.4.  Tested against ML Server 9.0-3.1 on RH7 and java 1.8.0_151-b12 on Windows 10 Home.
> fix #867--make getString work like getContentAs(name,String.class)

- marklogic-client-api/src/main/java/com/marklogic/client/impl/DOMWriter.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DocumentMetadataHandleTest.java
- marklogic-client-api/src/test/resources/test.bin
Complex XML with namespaces were getting serialized incorrectly in the properties. This was found out by trying to write back properties that had extracted text. The root cause seemed to be parameters passed in the wrong order to a few functions. 
I believe so. This needs to be fixed in both the 3.x and 4.x releases.
Yes and I've added a unit test to cover this case. I did see some failures, but it appeared to be the same number of failures as before my changes.
4.0.4 and 3.0.8
MarkLogic 9.0-6 and 8.0-6
* Java …
> Fix XML serialization in DOMWriter

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/HandleAsTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1018
* Are you modifying the correct branch? "develop"
> provide missing configuration in DatabaseClientFactory.Bean

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/StringQueryHostBatcherTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentWriteOperation.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteOperationImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteSetImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/WriteBatcherTest.java
Copyright upgrade
Yes
No
5.1.0
NA
NA
> updating copyright to 2020

- marklogic-client-api/src/test/java/com/marklogic/client/test/document/DocumentWriteOperationTest.java
* What issue are you addressing with this pull request? forestCount in cluster envrionment
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes, develop
* Version of MarkLogic Java Client API (see Readme.txt) 5.2
* Version of MarkLogic Server (see admin gui on port 8001) 10.0 nightly
* Java version (`java -version`) 11
> test cleanup - forest count in cluster environment,  #1196

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/DataMovementManager.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/CtsQueryBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/QueryManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
* What issue are you addressing with this pull request? #1260 
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes, develop branch
* Version of MarkLogic Java Client API (see Readme.txt) latest, 5.3
* Java version (`java -version`) java 8
* OS and version - Mac
> Add CtsQueryBuilder for DMSDK in Java API #1260

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/RdtExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderBaseImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RdtExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/row/RowManager.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanExpressionTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
Implements the following client interfaces with unit tests and JavaDoc:
- RowManager generateView() and generateViewAs() methods
- The methods supporting "Redaction On Rows"
Support for existsJoin() and notExistsJoin() were checked in previously. 
Any concerns?
> #1294 client interface for generate view and redaction on rows

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
* What issue are you addressing with this pull request? #1291
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes, develop
* Have you run unit tests? (See CONTRIBUTING.md) yes, ran QueryBatcherTest.java. All tests passed.
* Java version (`java -version`) 8
* What Changed: What happened before this change? What happens without this change? - Before the error msg is at warn level, but now at debug level. Also added in the msg what maxDocBatchSize is. Now the logs look like "[Test worker] DEBUG c.m.c.d.impl.QueryBatcherImpl - docBatchSize is beyond …
> Change log msg from warn to debug level. Added what maxDocBatchSize is in the msg #1291

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/ExecEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/StringQueryDefinitionImpl.java
…teria #1290
* What issue are you addressing with this pull request? - #1290 
* Are you modifying the correct branch? (See CONTRIBUTING.md) - develop
* Have you run unit tests? (See CONTRIBUTING.md) - yes
* Version of MarkLogic Java Client API (see Readme.txt) - latest
* Version of MarkLogic Server (see admin gui on port 8001) - 10.0
* Java version (`java -version`) - 8
* OS and version - Mac
* What Changed: What happened before this change? What happens without this change? - When constructing a query with an empty string as criteria, it used to throw an exception at the docBatchSize part. Now it will throw an exception complaining about empty string.
> Throw an exception when constructing a query with empty string as cri

- build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
* What issue are you addressing with this pull request? Removeing JCenter from build.gradle and update okhttp-digest dependency
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-7.1
* OS and version - Windows
> Remove JCenter #1298 #1272

- gradle.properties
* What issue are you addressing with this pull request? - publish to maven-snapshot was failing without SNAPSHOT in version
* Are you modifying the correct branch? (See CONTRIBUTING.md) -- develop
* Have you run unit tests? (See CONTRIBUTING.md) - NA
* Version of MarkLogic Java Client API (see Readme.txt) - 5.3+
* Version of MarkLogic Server (see admin gui on port 8001) NA
* Java version (`java -version`) NA
* OS and version - NA
maven publish was failing for internal maven repository (maven-snapshot)
> updating SNAPSHOT in version

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/InputCaller.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/InputOutputCaller.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/OutputCaller.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/BaseCallerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOCallerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOInputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOOutputCallerTest.java
- marklogic-client-api/src/test/resources/dataservices/bulkIOAnyDocumentInputCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOAnyDocumentInputCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/bulkIOAnyDocumentInputOutputCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOAnyDocumentInputOutputCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/bulkIOAnyDocumentOutputCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOAnyDocumentOutputCaller.sjs
* What issue are you addressing with this pull request? #1296
* Version of MarkLogic Java Client API (see Readme.txt) latest
* Version of MarkLogic Server (see admin gui on port 8001) 10.0 
> add anyDocument interfaces and unit tests #1296

- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/MarkLogicVersion.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/MarkLogicVersionTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
I looked for an annotation-based approach, but that's not easily done with JUnit 4. So just putting an `if` statement at the start of each RowManagerTest test that should only run on ML 11 or higher.
> JAVA-252: Fixing failing tests on ML 10 nightly

- ml-development-tools/build.gradle
Per the docs at https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html . This should hopefully fix the error we're getting from the Gradle plugins site about hash collisions on javadoc and groovydoc.
> ml-development-tools now uses 1.0.0 of publish plugin

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
Additional changes:
- Documented the two new public methods in `PlanBuilderBase`
- Moved all `fromParam` tests into its own simple test class for faster execution and easier understanding of the tests
- Testing JSON, XML, TEXT, and BINARY
> JAVA-246: Can now bind attachments when using fromParam

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/QueryBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/RowBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/PointInTimeQueryTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherTest.java
Allows for client to perform subsequent operations using that same timestamp.
Note that QueryBatcher provides access to this via the argument passed to QueryBatchListener, though that of course requires a bit more effort for a user to get than simply calling getServerTimestamp after the job completes.
> JAVA-246: RowBatcher and QueryBatcher now provide access to timestamp

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ContentParam.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderBaseImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamWriteTest.java
- marklogic-client-api/src/test/ml-config/security/roles/rest-delete-graph.json
This feature is not yet complete as it's waiting on some fixes/enhancements in the REST API. But it's good incremental progress until those fixes occur. 
Summary of changes: 
- Added bindParam(param, DocumentWriteSet)
- Added colType(column, type, nullable) as a convenience
- Combined bindParam(param, AbstractWriteHandle) and bindParamAttachments into a single new method - bindParam(param, AbstractWriteHandle, map of column names to attachments)
- Added ContentParam implementation class to simplifying ferrying around content params and optional attachment maps
> JAVA-246: Can now execute write() plans

- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
`testRawSPARQLSelect` in `RowManagerTest` is still failing because it's getting back 18 rows instead of 2. I don't know the reason for this yet though, but at least it fails now with a better error message.
> Test fixes as of 10/06 build

- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOInputCallerTest.java
Also updated assertion on RowManagerFromParamWriteTest as a bug in the error message for that scenario was fixed
And tweaked the assertion in BulkIOInputCallerTest as the test failed intermittently, but the assertion error doesn't state how many documents were actually written
> Fixing RowManagerTest.testRawSPARQLSelect

- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
Also updated commons-io in functionaltests as 2.6 is 4 years old. This only impacts the tests, of course. 
Bumped up compileOnly spring-jdbc from 5.3.18 to 5.3.23. 
Bumped up json-schema-validator from 1.0.42 to 1.0.73, as 1.0.42 was pretty far behind. Will rely on Jenkins tests to verify that this is okay.
> Updating Jackson dependencies from 2.12.4 to 2.13.4

- marklogic-client-api/src/test/java/com/marklogic/client/test/AbstractRowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamWriteTest.java
Cutting down on some duplication across the RowManager tests. Also re-enabled the FromParam tests, as I don't think those are an issue, it's just some export tests that cause FromParam tests to later fail.
> Extracted AbstractRowManagerTest

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ContentParam.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocDescriptorUtil.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanDocDescriptorImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromDocDescriptorsTest.java
Not all tests can pass yet as they're waiting in some server fixes. 
Main code change is I extracted all the logic for constructing a doc descriptor from a DocumentWriteOperation and tossed it into DocDescriptorUtil so that it can be easily reused by both `bindParam` and `fromDocDescriptors`.
> JAVA-265: Initial support for fromDocDescriptors

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowsParamsBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/row/RowManager.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamWriteTest.java
Refactored `RowManagerImpl` by extracting `RowsParamBuilder`, which is now used to construct a set of params for invoking the rows endpoint. That makes the code more readable and cuts down on the number of methods with several arguments. 
Renamed `makeRequest` to `submitPlan` for better readability too.
> JAVA-235: Can now perform execute() on a plan

- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamWriteTest.java
When using `write()`, rows can now be returned.
> Updating tests based on 57902 fix

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/DeleteListenerTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/UrisToWriterListenerFuncTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBulkReadSample1.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBulkWriteWithTransactions.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientKerberosFromFile.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientWithKerberos.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestJacksonDateTimeFormat.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestMetadata.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOptimisticLocking.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestSSLConnection.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestSemanticsGraphManager.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestSparqlQueryManager.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ThreadClass.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ThreadSearch.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ThreadWrite.java
The intent is to get the TODO's to both a manageable and meaningful list. These TODO's for auto-generated catch statements and overridden methods in our functional tests are neither.
> Removing some obsolete TODO's

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractRowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerJoinDocColsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerRemoveTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowRecordTest.java
This makes it a lot easier to only run RowManager tests.
Also ignored 3 more tests that do an "export()" - those still cause a segfault on my Mac. Will un-ignore them once that segfault bug is fixed.
> Moved RowManager tests into its own package

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractRowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerJoinDocColsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerLockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerRemoveTest.java
Includes a few ignored tests that are waiting a server bugfix. 
Also added `op.fromDocUris(String... uris)` as syntactic sugar for what seems like a common use case. 
And some refactorings:
- Added the ML 11 check for several tests that didn't have it already
- Added `resultRows(plan)` to `AbstractRowManagerTest` to cut down on a bunch of duplication
> JAVA-238: Added support for lockForUpdate()

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/TransformDefinition.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/TransformDefinitionImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTransformDocTest.java
- marklogic-client-api/src/test/ml-modules/root/etc/optic/test/transformDoc-test.mjs
- marklogic-client-api/src/test/ml-modules/root/etc/optic/test/transformDoc-test.xslt
- marklogic-client-api/src/test/ml-modules/root/etc/optic/test/transformDoc-throwsError.mjs
Test refers to multiple bugs though that need to be fixed; these are being tracked in JAVA-267. 
Also added a `bindParam(String, AbstractWriteHandle)` method for when the user does not need to include any attachments - I was finding it ugly to keep passing in `null` as the 3rd arg.
> JAVA-241: Can now use transformDoc()

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocDescriptorUtil.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteOperationImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanDocColsIdentifierImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractRowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerLockForUpdateTest.java
This is necessary for when the user only wants a subset of descriptor columns, but doesn't need to map them - having to specify a map just for this use case would be very annoying. 
Also added DocumentWriteOperationImpl(uri, metadata, content) and added newWriteOp to get rid of a lot of duplication in tests.
> JAVA-246: Added docCols(String[])

- marklogic-client-api/src/test/ml-config/security/roles/rest-delete-graph.json
These are no longer needed now that write() uses an amp
> Removed write privileges

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractRowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerLockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerRemoveTest.java
"fromParam" made sense for the first few tests that were specific to fromParam. Using "acme" as a generic prefix that conveniently shows up near the top of the results when exploring in qconsole. 
This includes a commit from the 246-temporal branch, so the PR for that branch should be merged in first.
> Renamed test URI prefix from /fromParam/ to /acme/

- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocDescriptorUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanDocDescriptorImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/JoinDocColsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/LockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RemoveTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TransformDocTest.java
- marklogic-client-api/src/test/ml-config/security/roles/rest-delete-graph.json
- marklogic-client-api/src/test/ml-config/security/roles/test-rest-writer.json
- marklogic-client-api/src/test/ml-config/security/users/writer-no-default-permissions.json
Renamed a bunch of tests, dropping "RowManager" from them, and renamed the abstract base class to make it clear it's specific to Optic Update. 
Introduced a "writer-no-default-permissions" user so that by default, the user for Optic Update tests does not have any default permissions.
> More test fixes based on server updates

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanDocColsIdentifierImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/JoinDocColsTest.java
Realized that `docCols(String[])` wasn't needed, now that xs.string works when using `docCols(null, xs.stringSeq)`. 
Reworked `docCols(Map<String, String>)` into `docCols(Map<String, PlanColumn>)` so that qualified columns can be referenced.
> Adding several more joinDocCols tests

- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
Addresses CVE https://avd.aquasec.com/nvd/2022/cve-2022-42003/
> Bumping jackson-databind to 2.13.4.2

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TransformDocTest.java
- marklogic-client-api/src/test/ml-config/security/roles/test-rest-writer.json
And removing xdmp-invoke privilege from test-rest-writer . These fixes rely on the amp on "execute" in optic-amped.sjs being given the rest-reader-internal role.
Note that this will cause the transformDoc tests to fail for MJS transforms - https://bugtrack.marklogic.com/58123 will address that.
> Un-ignoring xslt tests

- ml-development-tools/src/main/kotlin/com/marklogic/client/tools/proxy/Generator.kt
This was producing a warning during the build process, which makes the Jenkins logs a bit harder to debug. Trivial to remove.
> Removed unused argument in Generator

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/MarkLogicVersion.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOpticOnCtsQuery.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOpticOnLexicons.java
These started breaking after the tests were updated to run on ML 11, so they now check to see what version of ML is being used.
> Fixing some Optic functional tests on ML 9/10

- Jenkinsfile
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/resources/test.properties
- marklogic-client-api/src/test/ml-schemas/tde/permissions.properties
Had to add "fastHttpPort" so that the deployed app server isn't used by tests that aren't ready for it yet.
> Fixing functional tests

- Jenkinsfile
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/MarkLogicVersion.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnLexicons.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnLiterals.java
- marklogic-client-api-functionaltests/src/test/resources/test.properties
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TraceLabelAndOptimizeTest.java
Summary:
- Added ML 11 check for TraceLabelAndOptimizeTest
- Adjusted testLiteralsWithColumnInfo based on different results from ML 10 and 11
- Removed ML 9 from regression suite; ML 9 users should be using Java Client 4.2.0
- Simplified plan in testRestrictedXPathPredicate, not sure why that's failing yet except that its failure is caused by a previous test :(
> Next batch of functional test fixes

- Jenkinsfile
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticEnhancements.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnFromSparql.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnTriples.java
This is a temporary fix; something about the "field" config causes from-triples to go crazy. 
Brought in ml-app-deployer so it's easier/faster to make updates via the Manage API. Which will be swapping out a lot of the existing bespoke calls to the Manage API with ml-app-deployer over time.
> Fixing Optic from-triples tests

- CONTRIBUTING.md
- README.md
Didn't want this buried in the README. It's a little awkward still because .github/CONTRIBUTING.md exists with a bunch of boilerplate on how to create and submit a PR. That can be cleaned up later. The key is for the top-level CONTRIBUTING.md to describe how to actually develop and test an enhancement. 
Also removed the "What's new" content from the README. This was a bit random - some for Java 4, some for Java 5.3. The CHANGELOG has all this data too, so I removed it from the README.
> Extracted CONTRIBUTING.md info 

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestJSResourceExtensions.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/JavascriptResourceExtension.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/ResourceExtension.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/extension/BatchManager.java
- marklogic-client-api/src/main/java/com/marklogic/client/extensions/ResourceServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ResourceServicesImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ResourceServicesTest.java
Was able to remove this completely in OkHttpServices, as the argument wasn't used for anything. But can't remove it from ResourceServices since that's a public interface. So deprecating the argument in the 6 methods that have it. 
Adjusted each test and example not to pass in a mimetype argument anymore; those were misleading since it implied that the argument was having some impact.
> #1036: Deprecated unused mimetypes argument in ResourcesServices

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
This addresses a gap in the docs where we've never explained how to include JAXB if a user is using Java 11 or 17 and wishes to use the JAXB support in the Java Client. 
Can also now build and run all the tests using Java 11 or 17 (we've only used Java 8 before). That simply required the following:
- Don't fail the build on javadoc errors; Java 11 is much more particular about these, and we ought to do a cleanup of these errors soon, but we can ignore them for now
- Bumped up Gradle wrapper version to the latest 7.x; to build and run on Java 17, need at least Gradle 7.3
- Bumped up Mockito from the very, very old mockito-all dependency (last updated in 2015) to the latest ones; this fixed a simple problem with Mockito that popped up when testing with Java 11 and Java 17
- Added a …
> Updated README to address how to use Java Client on Java 11 and 17

- Jenkinsfile
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
Also fixed a bug in the error handling where a `FailedRequest` was constructed and populated, but it was not actually passed into the `FailedRequestException`, thereby causing a null-pointer error when certain parts of the `FailedRequestException` were added.
> Improved test for HTTP chunking

- Jenkinsfile
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ApplyTransformTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
Root cause was that they were ignoring URIs that intermittently failed due to the InterruptedException. These URIs were being set to the failure handler, so they weren't being dropped. The tests just needed to account for them. 
Also made both of these extends AbstractFunctionalTest so that they run a lot faster now.
Fixed a typo in Jenkinsfile too.
> Fixing stop-transform job tests

- marklogic-client-api-functionaltests/build.gradle
Temporarily adding that to PR pipeline so I can immediately run those tests
> Excluding tests from runSlowFunctionalTests

- CONTRIBUTING.md
- gradle.properties
- marklogic-client-api/build.gradle
Tweaks:
- Provided Java version guidance in CONTRIBUTING
- Modified how the JAXB dependencies are declared in build.gradle to match what's in the README (and the shorter syntax is easier to read/understand too)
> Bumping to 6.0.0, couple minor tweaks

- Jenkinsfile
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/ColumnInfo.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnCtsQuery.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnLexicons.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnLiterals.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnTriples.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnViews.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
I opened BUG-60065 to capture the "null row" issue that may still cause the test to TestOpticOnLiterals to fail, as it relies on an orderBy for a few plans.
> Fixing tests failing on 11-nightly

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
Intent is to make adding token-based auth simpler by making the "connect()" method easier to read and also making it possible to reuse the code for creating a new OkHttpClient.Builder and configuring it. 
Refactored a couple test methods to use ManageClient instead of verbose custom code for talking to Manage API.
> DEVEXP-146: Extracted private methods from OkHttpServices.connect

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/ClientApiFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestBulkWriteWithTransformations.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestDatabaseAuthentication.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestHandles.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestPartialUpdate.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestRuntimeDBselection.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
The intent is to make it simple to add a basePath in a follow up PR. No functionality change otherwise, just funneling every DatabaseClient construction via one method. 
"Slow" functional tests aren't impacted yet as it's not likely that we'll test those yet via the reverse proxy server. That's because they're hitting a variety of ports - which they don't need to do, but each needs to be refactored first.
> Refactoring fast functional tests to create client via one method

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/ClientApiFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestBulkWriteWithTransformations.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestDatabaseAuthentication.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestHandles.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestPartialUpdate.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestRuntimeDBselection.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/FailedRequestTest.java
These are all changes I've made on the basePath branch, but they are general test improvements that can be made before adding basePath, which will simplify that PR. 
Summary:
- Replaced usage of 8000 with standard functest port
- Made several improvements to ClientApiFunctionalTest, including adding a method for building a URL, which will be modified soon with basePath
- More cleanup in ConnectedRESTQA, including using ManageClient and did some renaming as well
- Removed pointless test from FailedRequestTest that was verifying that the REST API doesn't work on the Admin port; we can safely assume that any non-REST-API server will not work!
> More test refactoring before basePath PR

- Jenkinsfile
- gradle.properties
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/ClientApiFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientConnection.java
- marklogic-client-api-functionaltests/src/test/resources/test.properties
- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClient.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/HttpUrlBuilder.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/NewBaseUrlTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/NewDataServicesBaseUrlTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/HandleAsTest.java
- test-app/build.gradle
- test-app/src/main/java/com/marklogic/client/test/ReverseProxyServer.java
- test-app/src/main/ml-config/servers/java-functest.json
- test-app/src/main/ml-config/servers/java-unittest.json
The app changes were fairly simple here, with the most notable part being the addition of HttpUrlBuilder to encapsulate the logic for building a base URL, which has to account for basePath now. Added a bunch of unit tests for this too. 
Most of the rest of this PR is test stuff, specifically the new support for setting up a reverse proxy server and configuring the tests to use that server instead of talking to ML directly.
> DEVEXP-144: DatabaseClient now supports basePath

- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/OkHttpUtil.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/SSLSocketFactoryDelegator.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/SocketFactoryDelegator.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/CheckSSLConnectionTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/junit5/RequireSSLExtension.java
- marklogic-client-api/src/test/resources/logback-test.xml
This is a pure refactor, no functionality change. The intent is to make it easy for the upcoming MarkLogic cloud authenticator to reuse this code for making an HTTPS call to get a token.
> DEVEXP-143: Extracted methods for constructing an OkHttp Client

- gradle.properties
- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/MarkLogicCloudAuthenticationDebugger.java
Only downside is there's not yet a way to do this in an automated test against a real cloud instance. So relying on small unit tests and manual testing for now.
> DEVEXP-143: Now supporting authentication for MarkLogic Cloud

- build.gradle
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocDescriptorUtil.java
Moved the global dependencies to the precise places where they're needed to minimize confusion. Removed usage of StringUtils in DocDescriptorUtil, which was passing in the tests but failed in the real world since commons.lang3 is a compileOnly dependency.
A PR coming soon will move all the cookbook examples to a separate project, allowing us to get rid of several of these compileOnly dependencies to further avoid the chance of this bug occurring again.
> DEVEXP-149: Fixing buggy usage of StringUtils

- NOTICE.txt
- examples/build.gradle
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
- pom.xml
Also changed all dependencies to use the shorter syntax instead of including the words group/name/version. 
Bumped logback to 1.3.5 as well. And mockito to 4.10.0. 
And bumped json-schema-validator to 1.0.76 so that it also is using Jackson 2.14.
> Bumping Jackson to 2.14.1

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/ClientApiFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/data/api/TestE2EIntegerParamReturnDoubleErrorCond.sjs
Increased the sleep amount to hopefully avoid intermittent failure
> Disabling TestE2ENumberOfConcurrentUsers

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
Also marked the externalName stuff in the Bean class as deprecated; it should have been marked as deprecated back when the other things were deprecated since the `externalName` value isn't even used anywhere.
> DEVEXP-143: Added 'since' annotations

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherTest.java
Logging the batchSize at the info level is confusing to a user, who will most likely see a value very different from what they provided via `withBatchSize`. 
And changed the "current batch" logging from info to debug. This logging is fairly meaningless to a user, who has no idea what lower/upper bounds refer to. And if the user wants to see logging for each batch, they can simply add their own listener.
> Tweaking logging of batches in RowBatcherImpl

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherInitialQueryFailsTest.java
Addresses DEVEXP-147 (internal bug).
> #1327 QueryBatcher now stops when query fails

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/RowBatcherFuncTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherFailureTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherTest.java
This test now produces a real failure that results in the onBatchFailure listener being invoked. 
We had about a dozen tests calling onBatchFailure before, but none of them were actually doing something to cause the failure listener to be invoked. Tellingly, removing the `onBatchFailure listener` used in each of these tests still resulted in the tests passing, which confirms that the listeners were never being invoked. So the onBatchFailure call was removed from each of these tests to prevent anyone from thinking it was actually being tested in those tests.
> Added test for onBatchFailure

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/resources/test.properties
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/CheckSSLConnectionTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientFactoryTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/HandleAsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ResourceServicesTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/SemanticsPermissionsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
Also added a `DatabaseClientBuilder`, as I found that to greatly simplify our tests that construct clients in a variety of ways. Helps shield callers from having to know all the property names as well.
> DEVEXP-164: Added new factory method for DatabaseClient

- marklogic-client-api/src/main/java/com/marklogic/client/extra/okhttpclient/OkHttpClientBuilderFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/OkHttpUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/extra/okhttpclient/OkHttpClientBuilderFactoryTest.java
This is intended for ml-app-deployer and is in the "extra" package, which is pseudo-public - it's public, but with a caveat that you'll need to bring your own OkHttp dependency to compile against it and it may not work in a future version.
> DEVEXP-169 Extracted method for building an OkHttpClient

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/extra/okhttpclient/OkHttpClientBuilderFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/OkHttpUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/extra/okhttpclient/OkHttpClientBuilderFactoryTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
443 is written in stone for now, and thus the UX can be simpler by forcing the port to that value.
> Forcing port to 443 when using MarkLogic cloud authentication

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestDatabaseAuthentication.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestRuntimeDBselection.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
Syntatic sugar for when the client knows the desired security context type.
> Added more builder methods

- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
Ran into this while testing, where I was providing both a protocol and a "trust all" trust manager, but the builder failed to create a client. In this scenario, the builder is able to initialize the SSLContext itself since it has a trust manager from the user, so it now does so.
> Builder now inits SSL context when protocol and trust manager exist

- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/OkHttpUtil.java
Discovered this while doing some manual testing. The main ML Cloud instance that has been used for testing is not verifying certificates, and thus this line of code for configuring an SSL socket factory was not required. But if certificates are verified (which I ran into while doing some local testing using an emulated ML Cloud instance), we'll presumably want to construct an SSL socket factory using the same SSLContext and TrustManager that the Java Client uses when it constructs a DatabaseClient. 
Can only test this via manual testing, until we have a way to run automated tests against an ML Cloud instance.
> Applying SSL context and trust manager to "/token" call

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
The check is now made in `DatabaseClientPropertySource`, which is at a lower level than `DatabaseClientBuilder`. This ensures that e.g. an ml-gradle user gets the benefit of not having to specify "sslProtocol=default" if their intent is to use their JVM's default truststore. 
Also improved the type-checking in DatabaseClientPropertySource so that a friendly error message is thrown for any value that is of an incorrect type.
> Improving how cloud auth applies default SSLContext

- test-app/build.gradle
- test-app/gradle.properties
- test-app/src/main/java/com/marklogic/client/test/ReverseProxyServer.java
This supports testing ml-gradle where a user wants to both deploy a REST app server and load REST extensions, which requires loading them via that REST app server. The user will need to define `restBasePath` . The RPS now makes it easy to define a mapping from the value of `restBasePath` to whatever port the REST app server is listening on.
> Added custom mappings to reverse proxy server

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientConnection.java
- marklogic-client-api-functionaltests/src/test/resources/test.properties
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
Based on review of Node Client. authType now seems preferable because:
1. It's consistent with the Node Client
2. It's shorter and easier to remember/type
3. All concrete impls of SecurityContext are suffixed with "AuthContext"
> Renamed securityContextType property to authType

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/EvalTest.java
Did some formatting and simplifying of `postIteratedResourceImpl` too.
> DEVEXP-191 Ensuring eval errors are returned as JSON

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestDatabaseAuthentication.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/eval/ServerEvaluationCall.java
These don't work because they don't provide a security context. And since the 4.2.0 release and a change to OkHttpServices on 2019-01-07 that made a security context required, they haven't worked. I was going to deprecate them initially, but in the event that a pre 4.2.0 user upgrades directly to 6.1.0, I think a compile time error would be far better than waiting for either method to fail at runtime (and both are guaranteed to fail).
> Removed factory methods that have been broken since 4.2.0

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/MarkLogicCloudAuthenticationDebugger.java
I realized that `withMarkLogicCloudAuth` was inconsistent with how "cloud" is consistently used instead of "MarkLogic Cloud". Doesn't impact any libraries.
> Renamed to withCloudAuth

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/datamovement/ExportBatchesTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ExportListener.java
> DEVEXP-363 ExportListener now provides access to DocumentPage

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
Changes:
- Removed schemaName/viewName; they did not need to be class fields
- Marked 3 class fields as `final` to make it clear they're initialized in the constructor
- Changed "sucess" to "success"
> Small cleanup of RowBatcherImpl

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
Removed `rowsClass` as a class field, only needs to be a local variable. Extracted `validateRowsHandle` so the constructor is easier to understand.
> Cleaned up validation of rowsHandle in RowBatcherImpl

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementManagerImpl.java
`basePath` was not being carried forward from the primary client. We can't write an automated test for this as the code requires a second host to exist. I'm going to test it out manually today via a 2-node cluster.
> DEVEXP-402: Fixing creation of client in DMSDK

- examples/build.gradle
- gradle.properties
- marklogic-client-api/build.gradle
- pom.xml
And a few other patch upgrades. Also set version to 6.2-SNAPSHOT in preparation for a 6.2.1 release.
> Bumping OkHttp to 4.11, Jackson to 2.14.3

- test-app/build.gradle
This addresses CVE in https://issues.redhat.com/browse/UNDERTOW-2212 .
Note that undertow is only used in the test application and is not part of any production code.
> Bumping undertow from 2.2.21 to 2.2.24

- marklogic-client-api/src/main/java/com/marklogic/client/io/DocumentMetadataHandle.java
Reason is that when this occurs in a DMSDK setting, only the message is logged, which isn't helpful at all for debugging.
> Improved error message when metadata serialization fails

- marklogic-client-api/src/test/java/com/marklogic/client/test/CheckSSLConnectionTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/junit5/RequireSSLExtension.java
Figured out the plumbing for doing this with the Manage API, figured I should document it via a test here.
> Added test for a custom X509TrustManager

- examples/build.gradle
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- test-app/build.gradle
Latest OkHttp 4.x is still on 3.2.0, which is affected by https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKIO-5820002 . 
Bumped up patch version of a few other dependencies as well; those only impact test and build dependencies and do not impact anything that's published.
> Forcing usage of okio 3.4.0

- examples/build.gradle
- examples/src/main/java/com/marklogic/client/example/cookbook/ConfigureOkHttp.java
This is for customers that do not want responses to be gzip-encoded.
> Added example of removing the Accept-Encoding header

- marklogic-client-api/src/test/java/com/marklogic/client/test/SemanticsPermissionsTest.java
- test-app/src/main/ml-config/security/roles/java-test-delete-graph.json
- test-app/src/main/ml-config/security/roles/java-test-delete-temporal.json
- test-app/src/main/ml-config/security/roles/java-test-evaluator.json
- test-app/src/main/ml-config/security/roles/java-test-read-privileged.json
- test-app/src/main/ml-config/security/roles/java-test-write-privileged.json
- test-app/src/main/ml-config/security/users/read-privileged.json
- test-app/src/main/ml-config/security/users/rest-admin.json
- test-app/src/main/ml-config/security/users/rest-evaluator.json
- test-app/src/main/ml-config/security/users/rest-writer.json
- test-app/src/main/ml-config/security/users/write-privileged.json
- test-app/src/main/ml-config/security/users/writer-no-default-permissions.json
Avoids me thinking that e.g. "rest-evaluator" is an actual MarkLogic OOTB role. 
Tossed "java-test-" on as a prefix for several existing test-only roles.
> Renamed test roles to make it clear they're for the Java Client

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestBug18920.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOptimisticLocking.java
- marklogic-client-api/src/main/java/com/marklogic/client/ContentNoVersionException.java
- marklogic-client-api/src/main/java/com/marklogic/client/ContentWrongVersionException.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
Users no longer need to parse out exception messages. And now `TestOptimisticLocking` doesn't need to either, which allowed me to delete a bunch of code from it in favor of asserting on specific exception classes. 
This is a non-breaking change as the new exceptions are subclasses of `FailedRequestException` and contain the same error message.
> DEVEXP-469 Optimistic locking failures now throw concrete exceptions

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
Just unit tests for this until we have a Cloud instance for automated tests.
> DEVEXP-491 Can now configure token duration

- marklogic-client-api/src/main/java/com/marklogic/client/io/DocumentMetadataHandle.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/io/AddPermissionsFromDelimitedStringTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/io/DocumentMetadataHandleTest.java
This logic is from ml-javaclient-util, pretty much copy/pasted it and added tests. 
Also moved a test to the new "client.test.io" package as I don't like how we have a zillion tests in the "com.marklogic.client.test" package.
> DEVEXP-478 New addFromString method for permissions

- examples/src/main/java/com/marklogic/client/example/cookbook/ConfigureOkHttp.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/extra/okhttpclient/RemoveAcceptEncodingConfigurator.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientFactoryTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/extra/DisableGzippedResponsesTest.java
DatabaseClientFactory also supports multiple configurators now. This was essential for testing this new story, but it also aligns with what a user would expect a method named "add" to do (as opposed to "set"). `clearConfigurators` was also added both for testing purposes and so a user could remove all the configurators in case one or more should no longer be used.
> DEVEXP-562 Can now prevent Accept-Encoding=gzip header being used

- NOTICE.txt
- examples/build.gradle
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
- pom.xml
- test-app/build.gradle
This should be a no-op in terms of functionality; just bumping to get the latest security fixes in Jackson.
> Bumping Jackson dependencies to latest

- gradle/wrapper/gradle-wrapper.properties
This fixes the ml-development-tools tests that started failing when Jackson was bumped from 2.14.3 to 2.15.2. 50 tests failed with a message like this:
org.gradle.api.GradleException: Failed to create Jar file /space/Jenkins/workspace/va-client-api-regression_develop/java-client-api/ml-development-tools/build/tmp/test/work/.gradle-test-kit/caches/jars-9/ba996557e7d64c47da7a273bf722472f/jackson-core-2.15.2.jar.
I'm going to separately look into bumping the Kotlin dependencies of that project as the current ones are quite old.
> Bumping Gradle wrapper version

- ml-development-tools/build.gradle
Did not bump kotlin-stdlib though - 1.6.20 is what OkHttp 4.11.0 uses, so sticking with that for now.
> Bumped dependencies on dev-tools

- CONTRIBUTING.md
- ml-development-tools/src/test/example-project/README.md
- ml-development-tools/src/test/example-project/build.gradle
- ml-development-tools/src/test/example-project/src/main/ml-modules/root/inventory/lookup.api
- ml-development-tools/src/test/example-project/src/main/ml-modules/root/inventory/lookup.sjs
- ml-development-tools/src/test/example-project/src/main/ml-modules/root/inventory/service.json
- ml-development-tools/src/test/example-project/src/main/service.json
This could probably be expanded later, but I wanted to have something available for some basic manual/smoke testing.
> Added example project for testing ml-development-tools

- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SSLUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/CheckSSLConnectionTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/SSLTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
I was looking at this while analyzing support for 2-way SSL and I couldn't really understand what I wrote. So I refactored in the following way:
1. All construction for SSLContext/TrustManager is in buildSSLInputs.
2. There are 4 approaches, each clearly identified and implemented in its own method.
3. I moved the tests I use for verifying SSL support to a "test.ssl" package (no changes to the tests themselves).
This may actually fix a bug but I'm not certain. The bug would have been that "newCertificateAuthContext" was called before all the SSL-input logic had occurred, meaning that e.g. "default" as an sslProtocol value would not have impacted certificate authentication.
> Refactored logic for determining SSL inputs

- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
This catches the bug that I thought might have existed previous to the prior PR - it ensures that a user-defined TrustManager is used when an SSLContext is created based on a user-defined path for a PKCS12 file.
> Added test for certificate auth with file and password

- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkLoadFromJdbcRaw.java
- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/ExtractRowsViaTemplate.java
- marklogic-client-api/src/main/java/com/marklogic/client/query/StructuredQueryBuilder.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/BulkReadWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/MarkLogicCloudAuthenticationDebugger.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherFailureTest.java
See the comment for why it's deprecated; it presumably should never have been added in the first place as the `directory` method that receives a boolean is sufficient.
> #1603 Deprecating the `directory` method that receives a depth value

- marklogic-client-api/src/test/java/com/marklogic/client/test/junit5/RequireSSLExtension.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/OneWaySSLTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
Wanted to make the distinction between "OneWay" and "TwoWay" SSL tests.
> Renamed some things in SSL tests to improve clarity

- marklogic-client-api/src/main/java/com/marklogic/client/expression/CtsExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/FnExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/GeoExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/JsonExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/MapExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/MathExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/RdfExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/SemExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/SpellExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/SqlExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/XdmpExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/XsExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/CtsExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/FnExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/GeoExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/JsonExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/MapExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/MathExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RdfExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SemExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SpellExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SqlExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/XdmpExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/XsExprImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
This is all the code-generated stuff for DEVEXP-563. Will use a second PR for the manually-added stuff. 
Most of this is just copyright updates that were made by the code generator. 
Note that the code generator also updated PlanGeneratorTest. We have some manual mods in there so that some tests only run on MarkLogic 11, so I had to ensure those were retained.
> DEVEXP-563 Added geohashSubhashes to Optic plan builder

- gradle.properties
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SSLUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
Bumped the version to 6.4-SNAPSHOT as well so we can start using it in the Mule connector. 
The main value here is in TwoWaySSLTest, which can use these new properties instead of having to construct an SSLContext itself.
> DEVEXP-585 Can now configure 2-way SSL

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/datamovement/SetMaxBatchesTest.java
Documenting that setMaxBatches works with an iterator, but not with a query.
> Improved SetMaxBatchesTest

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteHostBatcherTest.java
- ml-development-tools/src/test/kotlin/com/marklogic/client/test/dbfunction/fntestgen.kt
> Fixing compiler warnings

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/StringSearchTest.java
Need to use "toString()" instead of "name()" so that "metadatavalues" is converted into "metadata-values". This works fine for reading documents but not for searching documents.
> DEVEXP-650 Fixing search that includes metadata values

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
Improved the existing `testSQL` and added tests for no rows being returned.
> DEVEXP-668 Added test for fromSql with no rows returned

- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
Not sure why `output` was ever set to `execute` - removing it does not cause any breaks on MarkLogic 11.1, and the 11-nightly (properly) throws an error when it's included. So removing it.
> Removing buggy usage of `execute`

- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/row/RowManager.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/LockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ResultRowsWithTimestampTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
Will submit a separate PR if/when the REST API is updated to throw a nicer error message.
> MLE-4119: User can now submit an Optic update plan

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SSLUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
For SSL and/or certificate authentication. Same approach as for a keystore, just for a truststore. 
Was able to reuse and improve `TwoWaySSLTest` by modifying it to use the key store as a trust store instead of using a "trust everything" trust manager.
> MLE-4116: Can now configure trust store

- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/row/RowManager.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/LockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ResultRowsWithTimestampTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
Going to do a 6.5.0 release to get the configurable truststore stuff out there. Need to hold off on v1/rows/update until 11.2 server release. 
This reverts 2 commits related to v1/rows/update.
> Reverting usage of v1/rows/update

- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ExportListenerTest.java
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
- test-app/build.gradle
Moved a brittle test to get it out of the PR test suite.
> Bumped dependencies

- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
Now using separate key and trust stores.
> Improved 2-way SSL test

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/test/java/com/marklogic/client/extra/okhttpclient/OkHttpClientConfiguratorTest.java
Ran into this with the Spark connector. We don't need the fix right away in the Spark connector, as we can synchronize the method that creates a client for now.
> Fixing bug with multiple threads using configurators

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnCtsQuery.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnLexicons.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnLiterals.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnTriples.java
These were removed as part of MLE-805 (formerly bug 60065) when these tests started failing on 11-nightly due to the orderBy. I added orderBy back and ran them on 11.1.0, 11-nightly, and 12-nightly, and they all passed.
> Adding back orderBy to some Optic tests

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/AwaitCompletionTest.java
The duration was previously mishandled, always resulting in a duration of 0 seconds.
> awaitCompletion now waits correctly

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/OpticPatchTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ValidateDocTest.java
Regenerated the code so that `onError` appears on `ModifyPlan` instead of `PlanBuilder`.
> MLE-13687 Able to use onError in plan builder

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
Ticket was about the "flushing queued docs" and info being way too noisy. Turned that to "trace" because it really is not important. Also turned down logging of threadCount/batchSize to the more appropriate debug level.
> MLE-13719 Turning down some logging

- marklogic-client-api/src/main/java/com/marklogic/client/document/GenericDocumentManager.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/BitemporalFeaturesTest.java
This has long been possible due to the sole implementation of GenericDocumentManager already implementing TemporalDocumentManager. Exposing this makes life simpler for connectors - particularly our Spark connector - by allowing them to depend on `GenericDocumentManager` for temporal operations instead of requiring either a JSON or XML document manager.
> MLE-13451 GenericDocumentManager now provides temporal methods

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/datamovement/QueryBatcherJobReportTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/WriteNakedPropertiesTest.java
The check on content being null was overly restrictive, as v1/documents allows for null content. This may cause some other DMSDK test to fail, in which case that test will be modified as null content is allowable here.
> Fixing bug where a 'naked' properties fragment cannot be written

- gradle/wrapper/gradle-wrapper.properties
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
- test-app/build.gradle
This will make supporting Java 21 easier, and also includes a few updates based on deprecated Gradle stuff. 
Also removed the "dist" stuff from marklogic-client-api. AFAICT, we have not updated nor published this zip in a long time. It seems intended for someone to download and have a local copy of the examples and javadocs. It causes issues with Gradle 8, so removing since we haven't used this in a long time.
> Bumping Gradle wrapper to version 8

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/BatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
Intent is to give us better visibility in the NiFi connector in particular as to when a WriteBatcher stops. 
Added a few methods to avoid direct access of the two AtomicBoolean variables.
> MLE-14416 Added info logging for start/stop in DMSDK batchers.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
Since the Jenkinsfile was mistakenly not using later Java versions correctly, this issue went undetected. The tests pass fine on Java 8, but 11 and higher require the core/max thread pool sizes to be adjusted in a specific order.
> Fixing thread pool size test failures

- marklogic-client-api/src/main/resources/META-INF/services/javax.ws.rs.ext.RuntimeDelegate
No idea why this was ever included in src/main . Will move it to src/test if it turns out any tests expect it to exist, but that is very unlikely since `MockRuntimeDelegate` does not exist anywhere.
> Removing invalid JAX-RS file

- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderBaseImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanSearchOptions.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/junit5/RequiresML12.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromSearchWithOptionsTest.java
Also adds a setting for BM25 Length Weight.
Added a couple of tests. These tests are of limited use here, but they do verify that "bm25" and "zero" are acceptable scoring options.
> Can now use search options in ML12 for BM25, Zero, and Random.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnViews.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/NewOpticMethodsInElevenDotOneTest.java
Reverting the recent change to PlanGeneratedTest, as the reverted copy runs fine on both Java 11 and the latest 12 nightly.
> Fixes for nightly tests

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/document/ReadDocumentPageTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
The test is disabled as I'm using it to do some refactoring first and then figure out how to use OkHttp's newish MultipartReader to fix this problem. 
Other changes:
1. Did some refactoring in `OkHttpServices` to make the code for reading a multipart response easier to read and eventually change to use OkHttp's MultipartReader.
2. Formatted Common and AbstractOpticUpdateTest.
> Added failing test for reading a DocumentPage

- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/document/ReadDocumentPageTest.java
This allows for setting `mail.mime.allowutf8` as a system property to work - that is, URIs can now contain UTF-8 characters instead of just US-ASCII. 
There is likely one more fix to make here. I ran all the Spark connector tests, and one test failed that involved hitting v1/rows. Going to debug that further and fix in a separate PR.
> MLE-15748 Using jakarta.mail instead of javax.mail

- NOTICE.txt
- examples/build.gradle
- gradle.properties
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
- pom.xml
- test-app/build.gradle
This is the latest version. We'll still ignore them in the Spark connector so we defer to whatever version Spark uses.
Not expecting any issues, assuming no breaking changes from Jackson 2.15 to 2.17.
> Bumped Jackson dependencies to 2.17.2

- marklogic-client-api/src/main/java/com/marklogic/client/MarkLogicServerException.java
- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentWriteOperation.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/SemValue.java
- marklogic-client-api/src/main/java/com/marklogic/client/extra/gson/GSONHandle.java
Comments:
1. `DocumentWriteOperation` - no comment as to why the enum value is deprecated, and it's referenced in multiple places that aren't deprecated.
2. `PlanBuilder` - not clear why `xmlAttributeSeq` is a problem.
3. `SemValue` - `stores` is used in multiple places.
4. `GSONHandle` - no comment as to why `getParser` is deprecated.
5. `MarkLogicServerException` - `getFailedRquest` is referenced in many places.
> Removing several deprecations

- examples/build.gradle
- marklogic-client-api/build.gradle
- test-app/build.gradle
This may be the root cause of the logging issue I'm running into with Flux - at least according to https://www.slf4j.org/codes.html#StaticLoggerBinder , as I verified that slf4j-api 1.x is sneaking onto the classpath. This should otherwise be a no-op for all of the Java Client, it doesn't care what version of slf4j-api it's using.
> Bumping slf4j-api to 2.0.16

- .gitignore
- CONTRIBUTING.md
- Jenkinsfile
- test-app/.env
- test-app/docker-compose.yaml
Switch to images and artifactory.
Take 4 - Removing mapped volumes.
> Converting Jenkinsfile to use a docker-compose file

- Jenkinsfile
Also remove a reference to a local forest directory now that we're using Docker volumes.
> Remove a set of tests that not required.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestEvalXquery.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBiTemporal.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/BinaryDocumentTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/io/DocumentMetadataHandleTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/VectorTest.java
- marklogic-client-api/src/test/resources/columnInfo/allTypes-marklogic-12.json
Creating a separate JIRA bug for the SSL tests.
> Regression test fixes

- Jenkinsfile
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnViews.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/OneWaySSLTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
Made a separate `runTestsWithReverseProxy` function.
Also bumped the PR build to use 12-nightly. Want to see if PlanGeneratedTest succeeds there.
> MLE-17306 Cleaning up Jenkinsfile

- marklogic-client-api/src/main/java/com/marklogic/client/query/StructuredQueryBuilder.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/StructuredSearchTest.java
These were all oversights in `StructuredQueryBuilder`.
> MLE-17044 Added trueQuery, falseQuery, and operatorState

- Jenkinsfile
- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/BaseTypeImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/VectorTest.java
I removed the restriction in BaseTypeImpl that requires every value to be a subclass of `BaseArgImpl`. That puts a big burden on the server in that it must accept "wrapped" values for primitive values. The server function `annTopK` does not support "wrapped" values for `k` or `queryTolerance`, and thus that restriction caused things to break.
Not sure we'll keep this change yet.
> MLE-17146 Added support for annTopK

- marklogic-client-api/src/main/java/com/marklogic/client/impl/IoUtil.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/PartIterator.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/InputStreamHandle.java
Finally makes use of the OkHttp MultipartReader to stream body parts instead of reading them all into memory. There's no test to be added here, as the only way to verify this is to try with a sufficient amount of data to cause an OutOfMemoryError. That will be verified manually instead. The existing regression tests will suffice to ensure that eval/invoke still work properly.
> MLE-19222 Eval/invoke now stream results

- marklogic-client-api/src/main/java/com/marklogic/client/eval/EvalResultIterator.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
Also added docs to ensure clients call `close()`, which they really ought to have been doing already given the name "iterator".
> Sanity check to ensure connection is closed

- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentDescriptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentManager.java
This is to provide some indication that a user can get null back for a read call when the document exists.
> MLE-18751 Added docs about descriptors and content versioning

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ConnectionString.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
Intent is to support this in places the upcoming query pipeline kit and other apps that want to create a client via properties.
Going to remove this support in the Spark connector next and reuse this.
> MLE-19240 Added marklogic.client.connectionString

- NOTICE.txt
- marklogic-client-api/build.gradle
This now fits the convention in our other repositories, only reporting on direct dependencies. Also removed a couple direct dependencies from build.gradle that are already brought in as transitive dependencies.
> Updating NOTICE file

- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/OneWaySSLTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
- test-app/docker-compose.yaml
Change the Docker stack name to help Sameera.
> Fix some timing issues with SSL tests.

- build.gradle
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/OneWaySSLTest.java
Trying this property to see if it works with Java 8.
> Enable TLSv1.3 with a different property.

- marklogic-client-api/src/test/java/com/marklogic/client/test/document/PatchDocumentTest.java
This was created many moons ago to help with designing Optic patch. The tests are all still relevant and are useful for documenting how the REST API patch operation works.
> Added tests for documenting how REST API patch works

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/QueryManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/QueryOptionsManagerImpl.java
Polaris was complaining about `null` being sent to the `receiveContent` method, but that needs to happen in at least one scenario - to trigger the "skipped" functionality on a QueryBatcher. So we'll need to ignore those warnings in Polaris.
> Few more null checks from Polaris

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestJSResourceExtensions.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnViews.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/HTTPSamlAuthInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/NodeConverter.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/QueryManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/QueryOptionsManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ResourceExtensionsImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/TransformExtensionsImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/MarkLogicCloudAuthenticationConfigurer.java
NodeConverter had a large amount of dead code - including a race condition! - that was deleted.
> Fixes for Polaris race conditions

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ExportToWriterListenerTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/StringQueryHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/TestSplitters.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/UrisToWriterListenerFuncTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/BulkIOCallersFnTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBiTempMetaValues.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBiTemporal.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientKerberosFromFile.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientWithKerberos.java
And also improved tear down methods - deleting the database via the ManageClient defaults to deleting all forests and replicas.
> Fixing WriteHostBatcherTest

- gradle.properties
- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/OkHttpUtil.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/ProgressDataCloudAuthenticationConfigurer.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/DatabaseClientPropertySourceTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/ProgressDataCloudAuthenticationConfigurerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/okhttp/TokenAuthenticationInterceptorTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/MarkLogicCloudAuthenticationDebugger.java
- test-app/README.md
- test-app/src/main/java/com/marklogic/client/test/ReverseProxyServer.java
Deprecates the MarkLogicCloudAuthContext class in favor of ProgressDataCloudAuthContext.
This change reflects the rebranding of MarkLogic Cloud to Progress Data Cloud and ensures that the client API aligns with the updated naming convention.
The deprecated class will be removed in a future release.
> MLE-21476 Deprecates MarkLogicCloudAuthContext

- NOTICE.txt
- marklogic-client-api/build.gradle
- pom.xml
And a couple other minor updates - note that the pom.xml is only used for GitHub's dependency feature.
> MLE-12345 Updating NOTICE file

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestAutomatedPathRangeIndex.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBiTempMetaValues.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBiTemporal.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientKerberosFromFile.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientWithKerberos.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestEvalwithRunTimeDBnTransactions.java
The "clear" that happens via DELETE v1/search causes intermittent failures on Jenkins.
> MLE-12345 Reworking how test plumbing clears a database

- marklogic-client-api/build.gradle
> MLE-12345 Fixed reference to opencsv

- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
Missed this reference in another build.gradle file
> MLE-12345 One more Black Duck fix

- ml-development-tools/src/test/example-project/build.gradle
Black Duck was complaining about a license issue in version 6.3.0 of ml-development-tools
> MLE-12345 Updated data services example project

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
The previous change caused a bunch of errors because the non-admin user couldn't delete everything. Also deleted some unused code that Intellij flagged.
> MLE-12345 clearDB now uses admin user

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
Deleting each URI fails for temporal URIs. Blah.
> MLE-12345 Going back to clearing the database

- Jenkinsfile
- settings.gradle
> MLE-12345:Using Java 17

- .gitignore
- docker-compose.yaml
Not sure how it's reporting on files under ".kotlin", so hopefully the gitignore addition will prevent that.
> MLE-12345 Polaris fixes

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/OkHttpUtil.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/RetryInterceptor.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
This avoids hardcoding it in the actual client and let's us still see the results for the tests.
Also fixed a warning from Polaris about the interceptor.
> MLE-23230 Applying RetryInterceptor in test plumbing

- .copyrightconfig
- .github/workflows/pr-workflow.yaml
> PDP-536: Adding copyright check

- Jenkinsfile
- build.gradle
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api/build.gradle
This avoids Gradle warnings and also gets the reverse proxy server tests working properly again.
> MLE-24505 Configuring custom Test tasks correctly

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/StreamingOutputImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/RetryIOExceptionInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/RetryableRequestBody.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/RowBatcherTest.java
And added comments to explain what the existing app-level retry support is doing vs what this for-now-undocumented interceptor will be doing.
> MLE-23230 Better name for retry interceptor

- Jenkinsfile
Verifying that all code can be compiled, even when running a subset of the tests.
> MLE-24505 Doing full build on PR pipeline

- Jenkinsfile
Also formatted the file so it's pretty. Only functional change though is on line 181, which ensures that the stage still completes even if tests fail.
> MLE-24579 Fixed PR test stage
