marklogic/java-client-api

- src/main/java/com/marklogic/client/io/InputStreamHandle.java
- src/main/java/com/marklogic/client/io/OutputStreamHandle.java
Not much exciting in this PR, just getting basic functionality of Jena integration off the ground.
@sammefford  I can perform the merge to develop and 3.0-develop if you give me the goahead.
> Two modifications to handles, so that Jena can read/write streams.

- .classpath
- .gitignore
- src/main/java/com/marklogic/client/impl/GraphManagerImpl.java
- src/main/java/com/marklogic/client/impl/JerseyServices.java
- src/main/java/com/marklogic/client/impl/RESTServices.java
- src/main/java/com/marklogic/client/impl/SPARQLQueryDefinitionImpl.java
- src/main/java/com/marklogic/client/impl/SPARQLQueryManagerImpl.java
- src/main/java/com/marklogic/client/semantics/SPARQLQueryDefinition.java
- src/test/java/com/marklogic/client/test/Common.java
- src/test/java/com/marklogic/client/test/SPARQLManagerTest.java
- src/test/java/com/marklogic/client/test/SPARQLQueryDefinitionTest.java
This commit has quite a few changes actually, but all good ones :)
1. fixes bug with SPARQL ASK.  previously was returning true all the time.
2. fixes typo/bug around using-named-graph-uri
3. implements replaceGraphs, deleteGraphs
> Tests for SPARQL, graphs implementation, Boolean query bugfix

- src/main/java/com/marklogic/client/impl/JerseyServices.java
- src/main/java/com/marklogic/client/impl/SPARQLQueryDefinitionImpl.java
- src/main/java/com/marklogic/client/semantics/SPARQLQueryDefinition.java
- src/test/java/com/marklogic/client/test/SPARQLManagerTest.java
- src/test/java/com/marklogic/client/test/SPARQLQueryDefinitionTest.java
- src/test/resources/bootstrap.xqy
A couple of bugs I found along the way too.
> Default inference, transaction tests for query

- src/test/java/com/marklogic/client/test/SPARQLManagerTest.java
- src/test/java/com/marklogic/client/test/SPARQLQueryDefinitionTest.java
Here's tests fixes for SPARQLQueryManager and SPARQLQueryDefinition
> Fix unit tests for sparql

- src/main/java/com/marklogic/client/impl/CombinedQueryBuilderImpl.java
- src/main/java/com/marklogic/client/impl/JerseyServices.java
- src/test/java/com/marklogic/client/test/SPARQLManagerTest.java
- src/test/java/com/marklogic/client/test/SPARQLQueryDefinitionTest.java
These commits add unit tests for USING and fix an assertion that changed (whitespace) with fast serialization of ntriples.
> Testing updates (USING) and combination query modifications

- src/main/java/com/marklogic/client/datamovement/DataMovementManager.java
- src/main/java/com/marklogic/client/datamovement/impl/DataMovementManagerImpl.java
- src/main/java/com/marklogic/client/datamovement/package-info.java
- src/main/java/com/marklogic/client/example/cookbook/datamovement/WriteandReadPOJOs.java
- src/main/java/com/marklogic/client/impl/CombinedQueryBuilder.java
- src/main/java/com/marklogic/client/impl/CombinedQueryBuilderImpl.java
- src/main/java/com/marklogic/client/impl/JerseyServices.java
- src/main/java/com/marklogic/client/impl/RawQueryDefinitionImpl.java
- src/main/java/com/marklogic/client/query/RawStructuredQueryDefinition.java
- src/main/java/com/marklogic/client/query/StructuredQueryBuilder.java
- src/main/java/com/marklogic/client/query/StructuredQueryDefinition.java
- src/test/java/com/marklogic/client/test/DeleteSearchTest.java
- src/test/java/com/marklogic/client/test/PojoFacadeTest.java
- src/test/java/com/marklogic/client/test/datamovement/ApplyTransformTest.java
- src/test/java/com/marklogic/client/test/datamovement/DeleteListenerTest.java
- src/test/java/com/marklogic/client/test/datamovement/ExportToWriterListenerTest.java
- src/test/java/com/marklogic/client/test/datamovement/LegalHoldsTest.java
- src/test/java/com/marklogic/client/test/datamovement/PointInTimeQueryTest.java
- src/test/java/com/marklogic/client/test/datamovement/QueryBatcherImplTest.java
- src/test/java/com/marklogic/client/test/datamovement/QueryBatcherIteratorTest.java
- src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
- src/test/java/com/marklogic/client/test/datamovement/ScenariosTest.java
- src/test/java/com/marklogic/client/test/datamovement/WriteBatcherTest.java
- src/test/java/com/marklogic/client/test/datamovement/javadocExamples/PackageExamples.java
- src/test/java/com/marklogic/client/test/datamovement/javadocExamples/UrisToWriterListenerExamples.java
@grechaw @georgeajit  @srinathgit @kkanthet more breaking changes.  I removed DatatMovementManager.newInstance and restricted newQueryHostBatcher to only StructuredQueryDefinition  and StringQueryDefinition.  @grechaw please comment that your code is ready to accept these changes, then @srinathgit or @georgeajit can merge this pull request.
> Merge final ea4changes

- pom.xml
Update dependency versions for:
|Dependency	| Resolved	|Newest	|
|---|---|---|
|junit	|4.11	| 4.12|
|xmlunit	|1.3	 |1.6|	
|logback-classic	|1.1.2	 |1.2.2|
jackson-dataformat-xml and jackson-dataformat-csv test dependencies should also be updated, but it should be done in tandem with updates for the other compile scope jackson dependencies
> update test dependencies

- CHANGELOG.md
> Turns issues into links

- pom.xml
Hi @grechaw and @sammefford
This PR will update the pom so that we can specify the snapshot and release nexus server URLS either at the command-prompt or through settings.xml
Thanks
Shiva
> Adding placeholders for snapshot and release repositories

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/DeleteListenerTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
> #920 - Fixed the hang on the single threaded case

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ProgressListener.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/ProgressListenerTest.java
This is take 2 on this PR - I closed https://github.com/marklogic/java-client-api/pull/928 and am submitting a clean PR that incorporates all of the comments/feedback from the original PR.
> Added ProgressListener

- marklogic-client-api/src/main/java/com/marklogic/client/CallParts.java
- marklogic-client-api/src/main/java/com/marklogic/client/SessionState.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/AbstractProxy.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/FailedRequest.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/JSONErrorParser.java
This pull request incorporates API First Base class integration into OkHttpservices. 
All the unit tests in both java client api and development tools subprojects were successful.
> #943 - API First Base class integration to OkHttpServices

- marklogic-client-api/src/main/java/com/marklogic/client/impl/FailedRequest.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
> #956 - Throw appropriate exceptions instead of RuntimeException

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/JobInformationRecorder.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/RecordJobInformation.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/RecordJobInformationTest.java
Added a cook book example to demonstrate how to record job information details into the database.
> #852 - Demonstrate how to record WriteBatcher/QueryBatcher

- CHANGELOG.md
- README.md
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
Also updated README and Changelog
> Cherry picked #881 and #920 for 4.1 release

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ApplyTransformTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/DeleteListenerTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/resources/test.properties
Test for https://github.com/marklogic/java-client-api/issues/999
Yes
4.1.1-develop
9.0-6.2
8
Windows 10
Added tests for issue #999
> Tests for issue #999

- marklogic-client-api/src/main/java/com/marklogic/client/query/StructuredQueryBuilder.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1012
* Are you modifying the correct branch? Develop
> Issue 1012

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/HTTPKerberosAuthInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
for develop branch)
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/995
* Are you modifying the correct branch? Yes, develop
> Enhance KerberosAuthContext to support all Krb5LoginModule options. (Fix

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/885
> Expose all SecurityContext details via getters #885

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/SSLTest.java
* What issue are you addressing with this pull request? SSLTestcase and https://github.com/marklogic/java-client-api/issues/885
> Adjusted the code and fixed testcase in SSLTest in accordance with issue - 885

- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobRunner.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/DHFPROD-1468
> Write before job document.

- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobRunner.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/DHFPROD-1468 and https://project.marklogic.com/jira/browse/DHFPROD-1471
> Before and After job documents.

- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobRunner.java
- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/ObjectLoader.java
https://project.marklogic.com/jira/browse/DHFPROD-1468 and https://project.marklogic.com/jira/browse/DHFPROD-1471
* Are you modifying the correct branch? "Develop-1275"
> Before and After Documents. (Corrected the errors)

- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobRunner.java
- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/ObjectLoader.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/DHFPROD-1504 and 
https://project.marklogic.com/jira/browse/DHFPROD-1469
* Are you modifying the correct branch? develop - 1275
> Tasks 1469 and 1504.

- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobLogger.java
- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobRunner.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-14 and https://project.marklogic.com/jira/browse/JAVA-15
> Initial Commit for Sprint 2 (Sub-tasks)

- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/CSVConverter.java
- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/CountInputStream.java
- ml-dhs-aws/src/main/java/com/marklogic/client/dhs/JobRunner.java
- ml-dhs-aws/src/test/java/com/marklogic/client/dhs/test/TestJobRunner.java
https://project.marklogic.com/jira/browse/JAVA-12 and
https://project.marklogic.com/jira/browse/JAVA-16
* Are you modifying the correct branch? develop-1275
> Sprint 2 - Java 12 and 16 (Also corrected the indentation). Continuation from pull request - 1041 

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/HTTPBasicAuthInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/HTTPKerberosAuthInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/HTTPSamlAuthInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
https://project.marklogic.com/jira/browse/JAVA-19,
https://project.marklogic.com/jira/browse/JAVA-20,
https://project.marklogic.com/jira/browse/JAVA-21 and 
https://project.marklogic.com/jira/browse/JAVA-22
> Test branch

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/HTTPSamlAuthInterceptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-29
> call a renewer when needed.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JacksonCSVSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/Splitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/WriteBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentWriteOperation.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/JacksonCSVSplitterTest.java
- marklogic-client-api/src/test/resources/data/test.csv
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-26
> Technical: Splitter with CSV Implementation

- marklogic-client-api/build.gradle
> Adding jackson-dataformat to build.gradle.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JacksonCSVSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/PeekingIterator.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-35
> refactor DHS S3CSV component to use CSV splitter.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-35
> Adding fix to add default metadata to all the remnant documents.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JacksonCSVSplitter.java
> Refactored CSV splitter.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JacksonCSVSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/Splitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/WriteBatcher.java
> Adding javadoc.

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/Utilities.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/ReaderHandle.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1055
> Improving the FileHandle efficiency.

- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallManagerTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-47
* Are you modifying the correct branch? develop-dsbulk
> CallBatcherTest for core functionality of bulk calls

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-49
* Are you modifying the correct branch? develop-dsbulk
> implemented getters for CallBatcher

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallManager.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/BytesHandle.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-58
* Are you modifying the correct branch? develop-dsbulk
>  CallBatcherBuilder.withDefaultArgs

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
queues values for batched calls
> reviewable implementation of batched parameter #1077

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatchedParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherDefaultArgsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/EndpointUtil.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-60, https://project.marklogic.com/jira/browse/JAVA-61
> unit tests for default parameters

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
https://project.marklogic.com/jira/browse/JAVA-52
* Are you modifying the correct branch? Yes - develop
> Implementing an argument generator callback.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherDefaultArgsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallbackGeneratorTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/EndpointUtil.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-63, https://project.marklogic.com/jira/browse/JAVA-64 and https://github.com/marklogic/java-client-api/issues/1084
> Unit test for callback generator and javadoc.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDoublePrecisionGeoOps.java
> testLinestringCrossesBox is now working.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDoublePrecisionGeoOps.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherDefaultArgsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/DataservicesPerForestTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/EndpointUtil.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-53
* Are you modifying the correct branch? develop-failover
> execute data services per forest

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
Please check for any issues in switching from set to map.  
(Which I should have used in the first place -- the set for checking whether a parameter name should have made that clear.)
> refactor call field representation

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/NodeConverter.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/FileHandle.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/marker/BufferableHandle.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/DataservicesPerForestTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/MultipleValuesAsArrayTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-62
* Are you modifying the correct branch? develop-failover
* Version of MarkLogic Server 9.0.9
> Assign multiple values as array instead of stream.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallFailureListener.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/CallManager.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatchedParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherDefaultArgsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallBatcherTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/CallbackGeneratorTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/DataservicesPerForestTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/MultipleValuesAsArrayTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-67
> Moving CallEvent from CallManager to CallBatcher.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/CallManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/BaseProxy.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/NodeConverter.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ValueConverter.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/MultipleValuesAsArrayTest.java
> Adding the conversion methods

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/QueryBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1095
> Limiting the maximum number of uris that can be collected.

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClient.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/636
* Are you modifying the correct branch? yes - develop
* Version of MarkLogic Java Client API 5.0
* Version of MarkLogic Server 10.0
> Adding "Test Connection" feature.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/QueryBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1095
* Are you modifying the correct branch? yes - develop
> Adding changes for QueryBatcher for max uris collection.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/InputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-82
* Are you modifying the correct branch?yes,  develop-72
> Adding InputEndpoint and InputEndpointImpl files.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-83
* Are you modifying the correct branch? yes, develop-72
> Adding BulkInputCallerImpl to InputEndpointImpl.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
> Adding few changes for setMaxUris and in the unit test.

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
> Commenting out maxUrisTestWithQueryTask to check jenkins job run time.

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1133
* Version of MarkLogic Java Client API - 5
* Version of MarkLogic Server - 10
> Adding method to change default assignment policy

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
> Adding few changes for maxUrisTestWithQueryTask unit test.

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
> changing counter to AtomicInteger.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/InputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-85 and https://project.marklogic.com/jira/browse/JAVA-87
> InputEndpointImpl method implementation and javadoc.

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
> Adjusting maxUrisTestWithQueryTask to be more dependant on the number of

- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/InputEndpointImplTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-86
> Unit Test for InputEndpoint implementation.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkInputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/IOTestUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/InputEndpointImplTest.java
- marklogic-client-api/src/test/resources/dataservices/bulkInputCallerImpl.api
- marklogic-client-api/src/test/resources/dataservices/bulkInputCallerImpl.sjs
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-86
* Are you modifying the correct branch? develop-72
* Version of MarkLogic Java Client API 5.0.1
* Java version 11.0.4
> Unit Test for bulk InputEndpoint implementation.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/OutputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-88, https://project.marklogic.com/jira/browse/JAVA-89 and https://project.marklogic.com/jira/browse/JAVA-93
* Are you modifying the correct branch? develop-72
> Output endpoint and output endpoint implementation along with the javadoc.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/OutputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-90 and https://project.marklogic.com/jira/browse/JAVA-91
* Are you modifying the correct branch? develop-72
* Version of MarkLogic Java Client API 5.0.1
* Java version 11.0.4
> Output Endpoint Implementation.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-85
* Version of MarkLogic Java Client API (see Readme.txt) 5.0.1
* Java version (`java -version`) 11.0.4
> Adding logic to awaitcompletion to process the last batch.

- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/OutputEndpointImplTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-92
> Unit Test for OutputEndpoint implementation.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkOutputCallerTest.java
- marklogic-client-api/src/test/resources/dataservices/bulkOutputCallerImpl.api
- marklogic-client-api/src/test/resources/dataservices/bulkOutputCallerImpl.sjs
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-92
* Version of MarkLogic Java Client API - 5.0.1
* Version of MarkLogic Server - 10.0
* Java version- 11
> Adding unit test for bulk output caller.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/OutputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-156
* Version of MarkLogic Server - 10
* Java version - 5.0.1
> Add BulkOutputCaller.next() for pulling output in Kafka.

- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkOutputCallerNext.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkOutputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/IOTestUtil.java
- marklogic-client-api/src/test/resources/dataservices/bulkOutputCallerNext.api
- marklogic-client-api/src/test/resources/dataservices/bulkOutputCallerNext.sjs
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-156
* Version of MarkLogic Java Client API 5.0.1
* Java version 11
> Adding unit test for bulkOutputCaller.next().

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/LineSplitter.java
* What issue are you addressing with this pull request? - To fix the error msg I missed in PR #1164
* Are you modifying the correct branch? develop branch
* Version of MarkLogic Java Client API - 5.0.1
* Version of MarkLogic Server - 10
* Java version - 11
* What Changed: I missed the error msg and 1 java doc modification in PR #1164. Fixing these 2 issues in this PR.
> Fixing error msg in PR #1164

- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentWriteOperation.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteOperationImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteSetImpl.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-159
* Version of MarkLogic Java Client API 5.0
* Java version 11.0
> sort documents by URI within a batch.

- marklogic-client-api/src/main/java/com/marklogic/client/pojo/PojoQueryBuilder.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1171
> Updating the url for "search-options".

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/WriteBatcherTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1163
* Are you modifying the correct branch? - develop
* Have you run unit tests? -  yes
* Version of MarkLogic Java Client API- 5.0
* Version of MarkLogic Server 10.0.2
* Java version - 11.0
> Fix to allow uris with different characters.

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/WriteBatcherTest.java
> Adjusting the uri for document.

- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentWriteOperation.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteOperationImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteSetImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/document/DocumentWriteOperationTest.java
> Adding changes to sort uris.

- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteSetImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/document/DocumentWriteOperationTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1168
* Are you modifying the correct branch? - develop
* Version of MarkLogic Java Client API - 5.0.1
* Java version - 11
> Adding variable "canSort".

- marklogic-client-api/src/test/java/com/marklogic/client/test/document/DocumentWriteOperationTest.java
> Adding license to DocumentWriteOperationTest.java

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/NodeOperation.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/XMLSplitter.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/XMLSplitterTest.java
- marklogic-client-api/src/test/resources/data/people.xml
* What issue are you addressing with this pull request? - JAVA-163
* Are you modifying the correct branch? (See CONTRIBUTING.md) - develop
* Have you run unit tests? (See CONTRIBUTING.md) - yes
* Version of MarkLogic Java Client API (see Readme.txt) - 5.0
* Version of MarkLogic Server (see admin gui on port 8001) - ML 10
* Java version (`java -version`) - 11
* OS and version - Linux
> Add class and unit test for JAVA-163

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOCallerImpl.java
> Changing "endpointState" variable to "workUnit" for null check.

- marklogic-client-api/build.gradle
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkExportServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkExportWithDataService.java
- marklogic-client-api/src/main/resources/scripts/bulkExport/readJsonDocs.api
- marklogic-client-api/src/main/resources/scripts/bulkExport/readJsonDocs.sjs
- marklogic-client-api/src/main/resources/scripts/bulkExport/service.json
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-166
* Are you modifying the correct branch? Yes, develop
* Version of MarkLogic Java Client API - 5.1.0
> Cookbook example bridging QueryBatcher to Data Services.

- marklogic-client-api/src/main/java/com/marklogic/client/alerting/RuleDefinition.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/util/Bootstrapper.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DOMWriter.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentMetadataPatchBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentPatchBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/DocumentMetadataHandle.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1153 and https://bugtrack.marklogic.com/53490
* Are you modifying the correct branch? yes. develop
* Version of MarkLogic Java Client API - 5.1.0
> Adding null check for XMLStreamWriter.writeCharacters().

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/QueryBatcher.java
> Changing javadoc for setMaxBatches.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JSONSplitter.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/JSONSplitterTest.java
- marklogic-client-api/src/test/resources/data/JsonMultiDiArray.json
- marklogic-client-api/src/test/resources/data/JsonSplitterArray.json
- marklogic-client-api/src/test/resources/data/JsonSplitterObject.json
- marklogic-client-api/src/test/resources/data/jsonCustMultiArray.json
* What issue are you addressing with this pull request?  JAVA-165
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes
* Version of MarkLogic Java Client API (see Readme.txt) 5.1
* Version of MarkLogic Server (see admin gui on port 8001) 
* Java version (`java -version`) 11
* OS and version macOS
> JSONSplitter JAVA-165

- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentManager.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/document/DocumentWriteOperationTest.java
* What issue are you addressing with this pull request? Add forestName to DocumentManager search method
* Are you modifying the correct branch? (See CONTRIBUTING.md) Yes, develop branch
* Version of MarkLogic Java Client API (see Readme.txt) 5.1
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-2
* Java version (`java -version`) 11
> code and unit test for #1196

- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/BulkExportWithDataServiceTest.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1209
* Are you modifying the correct branch? yes, develop
* Version of MarkLogic Java Client API - 5.1.0
* Version of MarkLogic Server 10.0
> Adding BulkExportWithDataServiceTest.

- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/BulkExportWithDataServiceTest.java
> Adding copyright to BulkExportWithDataServiceTest.java

- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/BulkExportOpticResultsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/BulkExportOpticResultsToWriterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/JdbcCookbookTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/MoveDataBetweenMarklogicDBsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/example/cookbook/RecordJobInformationTest.java
> Adding copyright.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/ExecEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/IOEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/InputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/InputOutputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/OutputEndpoint.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/ExecEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputOutputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkInputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkOutputCallerNext.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkOutputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/OutputEndpointImplTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-170 and https://project.marklogic.com/jira/browse/JAVA-171
* Are you modifying the correct branch? yes, develop
* Version of MarkLogic Java Client API - 5.1.0
* Version of MarkLogic Server 10.0.3
> Concurrency in bulk callers

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/ExecEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputOutputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOInputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOOutputCallerTest.java
- marklogic-client-api/src/test/resources/dataservices/bulkIOExecCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOExecCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/bulkIOInputCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOInputCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/bulkIOInputOutputCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOInputOutputCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/bulkIOOutputCaller.api
- marklogic-client-api/src/test/resources/dataservices/bulkIOOutputCaller.sjs
> Adding unit tests for bulk input, output, input-output and execute.

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
* What issue are you addressing with this pull request? Jenkins failure
> Fixing code for bulkIO next call.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/DataMovementManager.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JobTicket.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/RowBatchRequestEvent.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/RowBatchResponseEvent.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/RowBatchSuccessListener.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/RowBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/JobTicketImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/BatchPlanImpl.java
Working code for a basic request
> refactoring initial implementation of RowManager

- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOInputCallerTest.java
> Modifying the bulkIO input test case.

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/LineSplitter.java
* What issue are you addressing with this pull request? Blank lines are extracted as separate files. 
* Are you modifying the correct branch? (See CONTRIBUTING.md) Yes, develop branch
* Have you run unit tests? (See CONTRIBUTING.md) QA has tests to cover
* Version of MarkLogic Java Client API (see Readme.txt) 
> skip empty lines for LineSplitter #1232

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JSONSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/LineSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/UnarySplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/XMLSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ZipSplitter.java
* What issue are you addressing with this pull request? Make count multi-thread safe
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes, develop branch
* Have you run unit tests? (See CONTRIBUTING.md) Yes, current unit tests
* Version of MarkLogic Java Client API (see Readme.txt)  
> change count to ThreadLocal to make it multi-thread safe

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JSONSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JacksonCSVSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/LineSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/Splitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/UnarySplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/XMLSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ZipSplitter.java
* What issue are you addressing with this pull request? issue #1237 
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes, develop branch
* Have you run unit tests? (See CONTRIBUTING.md) yes, I ran all splitter unit tests
> rename inputName to splitFilename #1237

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/ExecEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/IOEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputOutputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/BulkIOOutputCallerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerExecEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerInputEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerInputOutputEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerOutputEndpointTest.java
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOExecCaller.api
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOExecCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOInputCaller.api
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOInputCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOInputOutputCaller.api
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOInputOutputCaller.sjs
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOOutputCaller.api
- marklogic-client-api/src/test/resources/dataservices/errorListenerBulkIOOutputCaller.sjs
* What issue are you addressing with this pull request? #1252 
* Are you modifying the correct branch? (See CONTRIBUTING.md) develop branch
* Version of MarkLogic Java Client API (see Readme.txt) 5.0
* Java version (`java -version`) 11
* OS and version MacOS
> Error Listener for Bulk Callers #1252

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JSONSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JacksonCSVSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/LineSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/Splitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/UnarySplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/XMLSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ZipSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/UriMakerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/JSONSplitterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/JacksonCSVSplitterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/LineSplitterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/UnarySplitterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/XMLSplitterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/ZipSplitterTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerInputEndpointTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerInputOutputEndpointTest.java
* What issue are you addressing with this pull request? #1237; #1245; #1246; Change count from ThreadLocal to long; Fix test expected results after refactoring of ResendableHandle.
* Version of MarkLogic Java Client API (see Readme.txt) up-to-date
* Java version (`java -version`) 
> Make a few changes to JavaDoc and tests

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/JSONSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/XMLSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ZipSplitter.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/BulkReadWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerInputEndpointTest.java
* What issue are you addressing with this pull request? 
> Add javadoc for getCount and minor fix for junit test

- marklogic-client-api/src/test/java/com/marklogic/client/test/dataservices/ErrorListenerExecEndpointTest.java
> Modify unit test to fix intermittent failure

- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/ExecEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/InputOutputEndpointImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/dataservices/impl/OutputEndpointImpl.java
* What issue are you addressing with this pull request? #1265 
* Are you modifying the correct branch? (See CONTRIBUTING.md) Yes, develop branch
* Have you run unit tests? (See CONTRIBUTING.md) Yes, all error listener unit tests
* Version of MarkLogic Java Client API (see Readme.txt) lastest
* Java version (`java -version`) 8
> Add null pointer check for getCallerThreadPoolExecutor() #1265

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/QueryBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/DataMovementServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/ConcurrencyTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/QueryBatcherTest.java
> Add currrent work of concurrency for DMSDK for suggestions ##1269

- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/WriteandReadPOJOs.java
> Fix the unit test which making regression hang.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/DeleteListenerTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatchImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/WriteandReadPOJOs.java
* What issue are you addressing with this pull request? The hang caused by last change
* Have you run unit tests? (See CONTRIBUTING.md) Yes, all unit tests pass
* Version of MarkLogic Java Client API (see Readme.txt) current
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-5.1
* Java version (`java -version`) 8
> Fix of hang issue for #1269

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/StringQueryHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/TestSplitters.java
> Comment out withThreadCount(1) in qa functional tests

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/DeleteListenerTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ExportListenerTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/StringQueryHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/TestSplitters.java
> Resolving testing issue after QueryBatcher concurrency is implemented

- NOTICE.txt
* What issue are you addressing with this pull request? Update Java API releasing notice, NOTICE.txt
* Are you modifying the correct branch? (See CONTRIBUTING.md) develop branch
* Have you run unit tests? (See CONTRIBUTING.md) No
* Version of MarkLogic Java Client API (see Readme.txt) latest
> Update Java API releasing notice, NOTICE.txt

- build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
Reverts marklogic/java-client-api#1304
This changes caused a line ending issue on windows platform.
> Revert "Remove JCenter #1298 #1272"

- build.gradle
- marklogic-client-api/build.gradle
- ml-development-tools/build.gradle
* What issue are you addressing with this pull request? @1298 #1272
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-7.1
* What Changed: What happened before this change? What happens without this change? - Previous change caused a line ending issue on windows. Trying to make this change in GitHub editor to eliminate the issue.
> Remove JCenter on Github site

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/QueryBatcher.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/ConcurrencyTest.java
* What issue are you addressing with this pull request? remove stale code
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-7.1
> remove stale code about throttleFactor

- NOTICE.txt
* What issue are you addressing with this pull request? update NOTICE.txt for 10.0-8 release
* Are you modifying the correct branch? (See CONTRIBUTING.md) yes
* Have you run unit tests? (See CONTRIBUTING.md) no need
* What Changed: What happened before this change? What happens without this change?update NOTICE.txt for 10.0-8 release
> update NOTICE.txt for 10.0-8 release

- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/row/RowManager.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
* What issue are you addressing with this pull request? #1329 expose op.columnInfo
* Version of MarkLogic Java Client API (see Readme.txt) latest
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-8
> #1329 expose op.columnInfo

- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
* What issue are you addressing with this pull request? Fix columnInfo unit test
* Have you run unit tests? (See CONTRIBUTING.md) yes, fixing this one
* Version of MarkLogic Java Client API (see Readme.txt) today's
> Fix unit test expected results

- NOTICE.txt
* What issue are you addressing with this pull request? Update NOTICE.txt file sent by legal team
* Have you run unit tests? (See CONTRIBUTING.md) No need
* Version of MarkLogic Java Client API (see Readme.txt) today's
> Update NOTICE.txt file sent by legal team

- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
- marklogic-client-api/src/test/resources/bootstrap.xqy
* What issue are you addressing with this pull request? #1342 
* Version of MarkLogic Java Client API (see Readme.txt) latest
* Version of MarkLogic Server (see admin gui on port 8001) 10.0-9.1
> Enabling compression and chunking #1342

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
* What issue are you addressing with this pull request? missing 0 arg overloaded method
* Version of MarkLogic Server (see admin gui on port 8001) 10.1 nightly
> #1347 op.sampleBy misses the 0 parameter overloaded method

- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java
* What issue are you addressing with this pull request? https://github.com/marklogic/java-client-api/issues/1345 
* Are you modifying the correct branch? Yes
* Version of MarkLogic Java Client API - 5.5.3
* Version of MarkLogic Server - 10.1
> Github issue - 1345 (DMSDK  hangs if one of the forest(s) goes offline).

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanDocColsIdentifier.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanDocColsIdentifierSeq.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanTransformDef.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanTransformDefSeq.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-222 
* Are you modifying the correct branch? yes, develop
> Adding new types for optic update.

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-232 
* Have you run unit tests?  Yes
* Version of MarkLogic Java Client API (see Readme.txt) - 5.3.3 
* Version of MarkLogic Server (see admin gui on port 8001) - ML 11.0
* Java version (`java -version`) - Java 1.8
> JAVA-232 : FromDocUris implementation in java-client-api

- ml-development-tools/build.gradle
Had a typo, which Jenkins found
> Fixing okhttp dependency in ml-development-tools

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanDocColsIdentifierImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanDocColsIdentifierSeqImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanDocColsIdentifierImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanDocColsIdentifierSeqImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerTest.java
Have only tested binding an array of JSON documents, need to cover a lot more scenarios. But wanted to get some initial feedback on the implementation approach.
> JAVA-246: Initial support for fromParam

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanRowColTypesImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanRowColTypesSeqImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanRowColTypesImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanRowColTypesSeqImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
Just did some renaming from PlanDoc to PlanRow. All tests passing again.
> Fixing RowManagerFromParamTest after code generation updates

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
This makes the new `bindParam` method consistent with the existing `bindParam` methods.
> JAVA-246: Added support for PlanParamExpr

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ParamAttachments.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RESTServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/RowManagerImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
Had to implement the methods in RawPlanImpl since it does not have a common parent with PlanSubImpl. Added a test for a raw plan to cover this new code.
> JAVA-246: Moving new bindParam methods to Plan

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanRowColTypesImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanRowColTypesImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/PlanRowColTypesSeqImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
Summary:
- Removed `schema` and `view`
- Defaulting `nullable` to `false`
- Defaulting `type` to `none`
> JAVA-246: Updating colTypes

- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerExportTest.java
Found these issues while testing out `export` on `fromDocDescriptors` on a separate branch.
> Added tests and fixes for exporting plans

- marklogic-client-api/src/main/java/com/marklogic/client/expression/GeoExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/XdmpExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/GeoExprImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanDocDescriptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanDocDescriptorSeq.java
- marklogic-client-api/src/main/javadoc/doc-files/types/cts_region.html
- marklogic-client-api/src/main/javadoc/doc-files/types/xs_boolean.html
- marklogic-client-api/src/main/javadoc/doc-files/types/xs_string.html
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-266
> Auto generation for fromDocDescriptors function.

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOpticOnViews.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerFromParamWriteTest.java
Also deleted obsolete Eclipse files, which shouldn't have been added to git (they were giving VSCode a real headache).
> Ignoring a couple Optic export tests

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/RowManagerRemoveTest.java
Will submit a future PR once the two referenced bugtrack tickets in the test are resolved.
> JAVA-240: Can now call remove()

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerFromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerLockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerRemoveTest.java
These now work due to several bugtrack bug fixes.
> Un-ignoring several tests

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UpdateUseCasesTest.java
> Starting test case with interesting update use cases

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/SchemaDefExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ErrorDispositionDefImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SchemaDefImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ValidateDocTest.java
- marklogic-client-api/src/test/ml-modules/root/validateDoc/permissions.properties
- marklogic-client-api/src/test/ml-modules/root/validateDoc/schematron.sch-validator.xsl
- marklogic-client-api/src/test/ml-schemas/validateDoc/jsonSchema.json
- marklogic-client-api/src/test/ml-schemas/validateDoc/permissions.properties
- marklogic-client-api/src/test/ml-schemas/validateDoc/schematron.sch
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/JAVA-242 
* Are you modifying the correct branch? yes "develop"
* Version of MarkLogic Server (see admin gui on port 8001) 11.0
* Java version (`java -version`)- java 1.8
> JAVA-242 : Implement "validateDoc" pipeline operation

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UpdateUseCasesTest.java
This runs fine due to a server fix now
> Fixing updateAndIgnoreNonExistentURIs

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DocumentWriteOperationImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/AbstractOpticUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/JoinDocTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RemoveTest.java
Temporal collection is now specified as a string
> JAVA-246: Can now write and remove temporal documents

- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestPointInTimeQuery.java
Test started failing eons ago when the call to get database counts failed because only XML format is supported. So rewrote that call to work on an XML response instead of JSON. Had to bring in JDOM2 to make life easy.
> Fixing TestPointInTimeQuery

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ValidateDocTest.java
> JAVA-242 : Tests for "validateDoc" pipeline operation

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/LockForUpdateTest.java
- marklogic-client-api/src/test/resources/logback-test.xml
Also bumped test logging down to info, as "debug" is very noisy for most tests
> Enhanced test for lockForUpdate

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamWriteTest.java
> Added more tests for only updating certain parts of a doc

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ApplyTransformTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QueryBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestCRUDModulesDb.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestEvalwithRunTimeDBnTransactions.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOpticOnCtsQuery.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOpticOnLexicons.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestOpticOnViews.java
The two "stop job" tests are still failing with off-by-one errors; I just added comments for those. The others were all easy fixes. The geospatial value changes are all due to an expected change in the server last night.
> Several fixes for functional tests

- marklogic-client-api/src/main/java/com/marklogic/client/impl/TransformDefImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/impl/TransformDefImplTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RemoveTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TransformDocTest.java
- marklogic-client-api/src/test/ml-config/security/roles/test-rest-writer.json
- marklogic-client-api/src/test/ml-modules/root/etc/optic/test/transformDoc-multipleRows.mjs
- marklogic-client-api/src/test/ml-modules/root/etc/optic/test/transformDoc-test.mjs
Also added rest-tracer for easier debugging with the test user.
> Added more transformDoc and remove tests

- marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/OpticUpdateExample.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UpdateUseCasesTest.java
- marklogic-client-api/src/test/ml-schemas/tde/zipcodes.tdex
Extracted this from a test in UpdateUseCasesTest
> JAVA-231: Added Optic Update example

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UpdateUseCasesTest.java
See https://bugtrack.marklogic.com/58137
> Ignoring writeNewDocsFromView

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilderBase.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/TransformDef.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/TransformDefImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanDocDescriptor.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanDocDescriptorSeq.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanRowColTypes.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanRowColTypesSeq.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanSchemaDef.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanSchemaDefSeq.java
> JAVA-244 : Add javadocs for all the accessor and pipeline operations

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TransformDocTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ValidateDocTest.java
> Modifying tests to verify https://bugtrack.marklogic.com/57987

- Jenkinsfile
Storing the Email address in Jenkins credentials and using the same in pipeline
> DEVO-682: Sending Email notifications

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
Will un-ignore this once the server bug is fixed
> Added ignored test for bug 58233

- Jenkinsfile
- marklogic-client-api-functionaltests/build.gradle
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestBug18993.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientKerberosFromFile.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientWithCertBasedAuth.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientWithKerberos.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestSSLConnection.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestSandBox.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UnnestTest.java
These are somehow still running in the Jenkins build, so using an @Ignore annotation
> Ignoring functional tests excluded in Gradle

- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/NODE-109
> Adding test for xdmp.unquote (NODE-109)

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/ClientApiFunctionalTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/Common.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/junit5/RequiresML11.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ExportTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromDocDescriptorsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamWriteTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/JoinDocColsTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/JoinDocTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/LockForUpdateTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RemoveTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/RowManagerTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TraceLabelAndOptimizeTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/TransformDocTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UnnestTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/UpdateUseCasesTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/ValidateDocTest.java
Now using a JUnit5 extension to avoid an "if" statement that was repeated 83 times.
> Refactord Optic tests requiring ML 11

- Jenkinsfile
Removed email notifications for now - we're not making use of them.
> Added phase to Jenkinsfile for running all tests with reverse proxy

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromParamWriteTest.java
Based on a review of how fromParam works
> Prettying up FromParam tests

- marklogic-client-api/build.gradle
Added note about Mockito 5.x requiring Java 11.
> Upgraded Mockito to 4.11

- examples/src/main/java/com/marklogic/client/example/cookbook/KerberosSSLClientCreator.java
Mostly just testing to ensure that the warning goes away in Snyk.
> Fixing warning in cookbook reported by Snyk

- marklogic-client-api/src/test/java/com/marklogic/client/test/StructuredSearchTest.java
Associated to #1640, trying to reproduce the error.
> Added test for and-not query

- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PatchBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderSubImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/type/PatchBuilder.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/OpticPatchTest.java
All of `PatchBuilder` and its impl was manually added. Was able to code generate the methods in the wrong place - PlanBuilder - and then move them over, and then manually implement them.
> MLE-13685 Added support for patch builder methods

- marklogic-client-api/src/test/java/com/marklogic/client/test/datamovement/XMLSplitterTest.java
- marklogic-client-api/src/test/resources/encoding/medline04.small.iso-8859-1.xml
Our Spark connector needs to do this - wanted to add an example of how to do it as a test.
> Verifies that XMLSplitter can use custom encoding

- marklogic-client-api/src/main/java/com/marklogic/client/expression/VecExpr.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/VecExprImpl.java
- marklogic-client-api/src/main/javadoc/doc-files/types/vec_vector.html
- marklogic-client-api/src/main/javadoc/doc-files/types/xs_anyAtomicType.html
- marklogic-client-api/src/main/javadoc/doc-files/types/xs_double.html
- marklogic-client-api/src/main/javadoc/doc-files/types/xs_unsignedInt.html
- marklogic-client-api/src/main/javadoc/doc-files/types/xs_unsignedLong.html
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
> MLE-15687 : Run auto-generation again to include server side code changes for 12-EA

- marklogic-client-api/build.gradle
> Using different impl of jakarta.mail

- README.md
- gradle.properties
- marklogic-client-api/src/main/java/com/marklogic/client/type/PlanSearchOptions.java
Replaced references to "6.7.0" to "7.0".
Replace 7.0-SNAPSHOT with 7.0 in properties.
Remove section on using JAXB from README.
Created ticket to replace: https://progresssoftware.atlassian.net/browse/MLE-15980
> Prepare for 7.0 release

- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/FromSearchDocsWithOptionsTest.java
Will enable this once the server nightly build has the fix.
> MLE-16147 Added disabled test for score-bm25 fix

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/AbstractFunctionalTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestOpticOnTriples.java
- marklogic-client-api/src/main/java/com/marklogic/client/expression/PlanBuilder.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PlanBuilderImpl.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/PlanGeneratedTest.java
> MLE-14438 : Use shortest-path function in Java plan builder

- .gitignore
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/search/SearchWithPageLengthTest.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
I think I'm covering the ways that this change might get called, though I'm not certain.
> Can now specify a page length of 0 when searching with OkHttpServices.

- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
I'm not sure what else, if anything, needs to be done for https://progresssoftware.atlassian.net/browse/MLE-19397
> Can now specify SSL Protocol when creating a CertificateAuthContext.

- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkLoadFromJdbcRaw.java
- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkLoadFromJdbcWithSimpleJoins.java
- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/DatabaseClientSingleton.java
- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/Employee.java
- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/ExtractRowsViaTemplate.java
- examples/src/main/java/com/marklogic/client/example/cookbook/datamovement/IncrementalLoadFromJdbc.java
- examples/src/main/java/com/marklogic/client/example/handle/DOM4JHandleExample.java
- marklogic-client-api/src/main/java/com/marklogic/client/alerting/RuleDefinition.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/XMLSplitter.java
- marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/RowBatcherImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/document/DocumentWriteOperation.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/NodeConverter.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/PojoRepositoryImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ServerConfigurationManagerImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/ServerEvaluationCallImpl.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/Utilities.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/XmlFactories.java
- marklogic-client-api/src/main/java/com/marklogic/client/io/SearchHandle.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/EvalTest.java
Should take care of all highs and mediums.
> MLE-17028 Fixing Polaris warnings

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestPartialUpdate.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java
- marklogic-client-api/src/main/java/com/marklogic/client/pojo/util/GenerateIndexConfig.java
Making sure resources are closed here.
Turned out I couldn't fix the issue in OkHttpServices without breaking a test. So added a comment instead. Cleaned up the test as well, which had a misleading name.
> More Polaris fixes

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestEvalJavaScript.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/rows/GraphQLTest.java
- test-app/src/main/ml-modules/root/etc/optic/test/transformDoc-multipleRows.mjs
- test-app/src/main/ml-modules/root/etc/optic/test/transformDoc-test.mjs
> MLE-21424 Fixing mjs-related tests

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/ExportToWriterListenerTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/QBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WBFailover.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteBatcherJobReportTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/datamovement/functionaltests/WriteHostBatcherTest.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientKerberosFromFile.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/TestDatabaseClientWithKerberos.java
This should eliminate most/all of the resource leaks I see when running tests that use this class. Still have a handful of methods left that use OkHttpClient directly.
This also eliminates a ton of redundant code.
> Refactor: Changing most of ConnectedRESTQA to use ManageClient

- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/fastfunctest/TestDatabaseClientConnection.java
- marklogic-client-api-functionaltests/src/test/java/com/marklogic/client/functionaltest/ConnectedRESTQA.java
- marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/DatabaseClientPropertySource.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/SSLUtil.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/DatabaseClientBuilderTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/OneWaySSLTest.java
- marklogic-client-api/src/test/java/com/marklogic/client/test/ssl/TwoWaySSLTest.java
- test-app/src/main/java/com/marklogic/client/test/ReverseProxyServer.java
Learned that this will allow Java to use the highest TLS protocol supported by the server.
> MLE-16818 Defaulting protocol to "TLS"

- Jenkinsfile
Was doing it from the test-app
> Fixing docker-compose call in Jenkinsfile

- marklogic-client-api/src/main/java/com/marklogic/client/ProgressDataCloudException.java
- marklogic-client-api/src/main/java/com/marklogic/client/impl/okhttp/ProgressDataCloudAuthenticationConfigurer.java
Unfortunately the mock tests do not cover these exceptions being thrown.
> Added better errors for PDC connection / auth issues
